(function() {
var _UDS_CONST_LOCALE = 'en';
var _UDS_CONST_SHORT_DATE_PATTERN = 'MDY'; 
var _UDS_MSG_SEARCHER_IMAGE = ('Image'); 
var _UDS_MSG_SEARCHER_WEB = ('Web'); 
var _UDS_MSG_SEARCHER_BLOG = ('Blog'); 
var _UDS_MSG_SEARCHER_VIDEO = ('Video'); 
var _UDS_MSG_SEARCHER_LOCAL = ('Local'); 
var _UDS_MSG_SEARCHCONTROL_SAVE = ('save'); 
var _UDS_MSG_SEARCHCONTROL_KEEP = ('keep'); 
var _UDS_MSG_SEARCHCONTROL_INCLUDE = ('include'); 
var _UDS_MSG_SEARCHCONTROL_COPY = ('copy'); 
var _UDS_MSG_SEARCHCONTROL_CLOSE = ('close'); 
var _UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS = ('Sponsored Links'); 
var _UDS_MSG_SEARCHCONTROL_SEE_MORE = ('see more...'); 
var _UDS_MSG_SEARCHCONTROL_WATERMARK = ('clipped from Google'); 
var _UDS_MSG_SEARCHER_CONFIG_SET_LOCATION = ('Search location'); 
var _UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP = ('Disable address lookup'); 
var _UDS_MSG_SEARCHER_NEWS = ('News'); 
function _UDS_MSG_MINUTES_AGO(AGE_MINUTES_AGO) {return ('' + AGE_MINUTES_AGO + ' minutes ago');} 
var _UDS_MSG_ONE_HOUR_AGO = ('1 hour ago'); 
function _UDS_MSG_HOURS_AGO(AGE_HOURS_AGO) {return ('' + AGE_HOURS_AGO + ' hours ago');} 
function _UDS_MSG_NEWS_ALL_N_RELATED(NUMBER) {return ('all ' + NUMBER + ' related');} 
var _UDS_MSG_NEWS_RELATED = ('Related Articles'); 
var _UDS_MSG_BRANDING_STRING = ('powered by Google'); 
var _UDS_MSG_SORT_BY_DATE = ('Sort by date'); 
var _UDS_MSG_MONTH_ABBR_JAN = ('Jan'); 
var _UDS_MSG_MONTH_ABBR_FEB = ('Feb'); 
var _UDS_MSG_MONTH_ABBR_MAR = ('Mar'); 
var _UDS_MSG_MONTH_ABBR_APR = ('Apr'); 
var _UDS_MSG_MONTH_ABBR_MAY = ('May'); 
var _UDS_MSG_MONTH_ABBR_JUN = ('Jun'); 
var _UDS_MSG_MONTH_ABBR_JUL = ('Jul'); 
var _UDS_MSG_MONTH_ABBR_AUG = ('Aug'); 
var _UDS_MSG_MONTH_ABBR_SEP = ('Sep'); 
var _UDS_MSG_MONTH_ABBR_OCT = ('Oct'); 
var _UDS_MSG_MONTH_ABBR_NOV = ('Nov'); 
var _UDS_MSG_MONTH_ABBR_DEC = ('Dec'); 
var _UDS_MSG_DIRECTIONS = ('directions'); 
var _UDS_MSG_CLEAR_RESULTS = ('clear results'); 
var _UDS_MSG_SHOW_ONE_RESULT = ('show one result'); 
var _UDS_MSG_SHOW_MORE_RESULTS = ('show more results'); 
var _UDS_MSG_SHOW_ALL_RESULTS = ('show all results'); 
var _UDS_MSG_SETTINGS = ('settings'); 
var _UDS_MSG_SEARCH = ('search'); 
var _UDS_MSG_SEARCH_UC = ('Search'); 
var _UDS_MSG_POWERED_BY = ('powered by'); 
function _UDS_MSG_LOCAL_ATTRIBUTION(LOCAL_RESULTS_PROVIDER) {return ('Business listings provided by ' + LOCAL_RESULTS_PROVIDER + '');} 
var _UDS_MSG_SEARCHER_BOOK = ('Book'); 
function _UDS_MSG_FOUND_ON_PAGE(FOUND_ON_PAGE) {return ('Page ' + FOUND_ON_PAGE + '');} 
function _UDS_MSG_TOTAL_PAGE_COUNT(PAGE_COUNT) {return ('' + PAGE_COUNT + ' pages');} 
var _UDS_MSG_SEARCHER_BY = ('by'); 
var _UDS_MSG_SEARCHER_CODE = ('Code'); 
var _UDS_MSG_UNKNOWN_LICENSE = ('Unknown License'); 
var _UDS_MSG_SEARCHER_GSA = ('Search Appliance'); 
var _UDS_MSG_SEARCHCONTROL_MORERESULTS = ('More results'); 
var _UDS_MSG_SEARCHCONTROL_PREVIOUS = ('Previous'); 
var _UDS_MSG_SEARCHCONTROL_NEXT = ('Next'); 
var _UDS_MSG_GET_DIRECTIONS = ('Get directions'); 
var _UDS_MSG_GET_DIRECTIONS_TO_HERE = ('To here'); 
var _UDS_MSG_GET_DIRECTIONS_FROM_HERE = ('From here'); 
var _UDS_MSG_CLEAR_RESULTS_UC = ('Clear results'); 
var _UDS_MSG_SEARCH_THE_MAP = ('search the map'); 
var _UDS_MSG_SCROLL_THROUGH_RESULTS = ('scroll through results'); 
var _UDS_MSG_EDIT_TAGS = ('edit tags'); 
var _UDS_MSG_TAG_THIS_SEARCH = ('tag this search'); 
var _UDS_MSG_SEARCH_STRING = ('search string'); 
var _UDS_MSG_OPTIONAL_LABEL = ('optional label'); 
var _UDS_MSG_DELETE = ('delete'); 
var _UDS_MSG_DELETED = ('deleted'); 
var _UDS_MSG_CANCEL = ('cancel'); 
var _UDS_MSG_UPLOAD_YOUR_VIDEOS = ('upload your own video'); 
var _UDS_MSG_IM_DONE_WATCHING = ('i\047m done watching this'); 
var _UDS_MSG_CLOSE_VIDEO_PLAYER = ('close video player'); 
var _UDS_MSG_NO_RESULTS = ('No Results'); 
var _UDS_MSG_LINKEDCSE_ERROR_RESULTS = ('This Custom Search Engine is loading. Try again in a few seconds.'); 
var _UDS_MSG_COUPONS = ('Coupons'); 
var _UDS_MSG_BACK = ('back'); 
var _UDS_MSG_SUBSCRIBE = ('Subscribe'); 
var _UDS_MSG_SEARCHER_PATENT = ('Patent'); 
var _UDS_MSG_USPAT = ('US Pat.'); 
var _UDS_MSG_USPAT_APP = ('US Pat. App'); 
var _UDS_MSG_PATENT_FILED = ('Filed'); 
var _UDS_MSG_ADS_BY_GOOGLE = ('Ads by Google'); 
var _UDS_MSG_SET_DEFAULT_LOCATION = ('Set default location'); 
var _UDS_MSG_NEWSCAT_TOPSTORIES = ('Top Stories'); 
var _UDS_MSG_NEWSCAT_WORLD = ('World'); 
var _UDS_MSG_NEWSCAT_NATION = ('Nation'); 
var _UDS_MSG_NEWSCAT_BUSINESS = ('Business'); 
var _UDS_MSG_NEWSCAT_SCITECH = ('Sci/Tech'); 
var _UDS_MSG_NEWSCAT_ENTERTAINMENT = ('Entertainment'); 
var _UDS_MSG_NEWSCAT_HEALTH = ('Health'); 
var _UDS_MSG_NEWSCAT_SPORTS = ('Sports'); 
var _UDS_MSG_NEWSCAT_POLITICS = ('Politics');
var b=void 0,f=null,h=encodeURIComponent,j=google_exportSymbol,aa=_UDS_CONST_SHORT_DATE_PATTERN,k=window,m=document,n=Math,ba=navigator,ca=parseInt,da=parseFloat,ea=_UDS_CONST_LOCALE,fa=decodeURIComponent;function ga(a,c){return a.input=c}function ha(a,c){return a.width=c}function o(a,c){return a.innerHTML=c}function p(a,c){return a.value=c}function ia(a,c){return a.type=c}function ja(a,c){return a.title=c}function r(a,c){return a.className=c}function ka(a,c){return a.checked=c}
function la(a,c){return a.next=c}function ma(a,c){return a.target=c}function na(a,c){return a.onclick=c}function oa(a,c){return a.display=c}function pa(a,c){return a.execute=c}function qa(a,c){return a.height=c}function ra(a,c){return a.root=c}
var s="appendChild",sa="push",ta="show",ua="clearTimeout",t="input",v="width",va="submit",wa="round",w="replace",xa="floor",ya="content",x="getElementById",za="offsetWidth",Aa="sessionStorage",y="value",Ba="indexOf",Ca="match",Da="focus",A="createElement",Ea="keyCode",B="firstChild",Fa="setAttribute",Ga="cloneNode",Ha="type",Ia="ServiceBase",C="getTime",Ja="getElementsByTagName",Ka="toString",D="length",La="title",E="prototype",F="cursor",Ma="className",Na="Version",Oa="checked",Pa="setTimeout",Qa=
"next",Ra="split",Sa="offsetParent",Ta="location",Ua="getComputedStyle",H="style",Va="close",Wa="body",Xa="removeChild",I="search",J="call",K="loader",Ya="currentStyle",Za="themes",$a="apply",ab="parentNode",L="CurrentLocale",M="execute",bb="height",N="root",cb="join",db="toLowerCase",eb="event",O;google[I].NoOldNames||(j("UDS_ServiceBase",google[K][Ia]),j("UDS_ApiKey",google[K].ApiKey),j("UDS_KeyVerified",google[K].KeyVerified),j("UDS_LoadFailure",google[K].LoadFailure),j("UDS_CurrentLocale",ea),j("UDS_ShortDatePattern",aa),j("UDS_Version",google[I][Na]),j("UDS_JSHash",google[I].JSHash));if(!P)var P=j;if(!Q)var Q=google_exportProperty;var R={blank:"&nbsp;"};R.image=_UDS_MSG_SEARCHER_IMAGE;R.web=_UDS_MSG_SEARCHER_WEB;R.blog=_UDS_MSG_SEARCHER_BLOG;R.video=_UDS_MSG_SEARCHER_VIDEO;R.local=_UDS_MSG_SEARCHER_LOCAL;R.news=_UDS_MSG_SEARCHER_NEWS;R.book=_UDS_MSG_SEARCHER_BOOK;R.patent="Patent";R["ads-by-google"]=_UDS_MSG_ADS_BY_GOOGLE;R.cse="Custom Search Control";R.save=_UDS_MSG_SEARCHCONTROL_SAVE;R.keep=_UDS_MSG_SEARCHCONTROL_KEEP;R.include=_UDS_MSG_SEARCHCONTROL_INCLUDE;R.copy=_UDS_MSG_SEARCHCONTROL_COPY;R.close=_UDS_MSG_SEARCHCONTROL_CLOSE;
R["sponsored-links"]=_UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS;R["see-more"]=_UDS_MSG_SEARCHCONTROL_SEE_MORE;R.watermark=_UDS_MSG_SEARCHCONTROL_WATERMARK;R["search-location"]=_UDS_MSG_SEARCHER_CONFIG_SET_LOCATION;R["disable-address-lookup"]=_UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP;R["sort-by-date"]=_UDS_MSG_SORT_BY_DATE;R.pbg=_UDS_MSG_BRANDING_STRING;R["n-minutes-ago"]=_UDS_MSG_MINUTES_AGO;R["n-hours-ago"]=_UDS_MSG_HOURS_AGO;R["one-hour-ago"]=_UDS_MSG_ONE_HOUR_AGO;R["all-n-related"]=_UDS_MSG_NEWS_ALL_N_RELATED;
R["related-articles"]=_UDS_MSG_NEWS_RELATED;R["page-count"]=_UDS_MSG_TOTAL_PAGE_COUNT;var fb=[];fb[0]=_UDS_MSG_MONTH_ABBR_JAN;fb[1]=_UDS_MSG_MONTH_ABBR_FEB;fb[2]=_UDS_MSG_MONTH_ABBR_MAR;fb[3]=_UDS_MSG_MONTH_ABBR_APR;fb[4]=_UDS_MSG_MONTH_ABBR_MAY;fb[5]=_UDS_MSG_MONTH_ABBR_JUN;fb[6]=_UDS_MSG_MONTH_ABBR_JUL;fb[7]=_UDS_MSG_MONTH_ABBR_AUG;fb[8]=_UDS_MSG_MONTH_ABBR_SEP;fb[9]=_UDS_MSG_MONTH_ABBR_OCT;fb[10]=_UDS_MSG_MONTH_ABBR_NOV;fb[11]=_UDS_MSG_MONTH_ABBR_DEC;R["month-abbr"]=fb;R.directions=_UDS_MSG_DIRECTIONS;
R["clear-results"]=_UDS_MSG_CLEAR_RESULTS;R["show-one-result"]=_UDS_MSG_SHOW_ONE_RESULT;R["show-more-results"]=_UDS_MSG_SHOW_MORE_RESULTS;R["show-all-results"]=_UDS_MSG_SHOW_ALL_RESULTS;R.settings=_UDS_MSG_SETTINGS;R.search=_UDS_MSG_SEARCH;R["search-uc"]=_UDS_MSG_SEARCH_UC;R["powered-by"]=_UDS_MSG_POWERED_BY;R.sa=_UDS_MSG_SEARCHER_GSA;R.by=_UDS_MSG_SEARCHER_BY;R.code=_UDS_MSG_SEARCHER_CODE;R["unknown-license"]=_UDS_MSG_UNKNOWN_LICENSE;R["more-results"]=_UDS_MSG_SEARCHCONTROL_MORERESULTS;
R.previous=_UDS_MSG_SEARCHCONTROL_PREVIOUS;la(R,_UDS_MSG_SEARCHCONTROL_NEXT);R["get-directions"]=_UDS_MSG_GET_DIRECTIONS;R["to-here"]=_UDS_MSG_GET_DIRECTIONS_TO_HERE;R["from-here"]=_UDS_MSG_GET_DIRECTIONS_FROM_HERE;R["clear-results-uc"]=_UDS_MSG_CLEAR_RESULTS_UC;R["search-the-map"]=_UDS_MSG_SEARCH_THE_MAP;R["scroll-results"]=_UDS_MSG_SCROLL_THROUGH_RESULTS;R["edit-tags"]=_UDS_MSG_EDIT_TAGS;R["tag-search"]=_UDS_MSG_TAG_THIS_SEARCH;R["search-string"]=_UDS_MSG_SEARCH_STRING;R["optional-label"]=_UDS_MSG_OPTIONAL_LABEL;
R["delete"]=_UDS_MSG_DELETE;R.deleted=_UDS_MSG_DELETED;R.cancel=_UDS_MSG_CANCEL;R["upload-video"]=_UDS_MSG_UPLOAD_YOUR_VIDEOS;R["im-done"]=_UDS_MSG_IM_DONE_WATCHING;R["close-player"]=_UDS_MSG_CLOSE_VIDEO_PLAYER;R["no-results"]=_UDS_MSG_NO_RESULTS;R["linked-cse-error-results"]=_UDS_MSG_LINKEDCSE_ERROR_RESULTS;R.back=_UDS_MSG_BACK;R.subscribe=_UDS_MSG_SUBSCRIBE;R["us-pat"]="US Pat.";R["us-pat-app"]="US Pat. App";R["us-pat-filed"]="Filed";R.dym="Did you mean: ";function gb(a,c){var d=function(){};d.prototype=c[E];a.prototype=new d;a[E].Aj=function(c){var d=Array[E].splice[$a](arguments,[1,arguments[D]]);return c[$a](a,d)}}var _json_cache_defeater_=(new Date)[C](),_json_request_require_prep=!0;function hb(a,c){var d;if(d=ib("msie"))d="msie 6.0"in jb?jb["msie 6.0"]:jb["msie 6.0"]=ba.appVersion[db]()[Ba]("msie 6.0")!=-1;d?k[Pa](S(this,kb,[a,c]),0):kb(a,c)}function lb(a){_json_request_require_prep=!1;hb(a,f);_json_request_require_prep=!0}
function kb(a,c){var d=m[Ja]("head")[0];d||(d=m[Wa][ab][s](m[A]("head")));var e=m[A]("script");ia(e,"text/javascript");e.charset="utf-8";var g=_json_request_require_prep?a+"&key="+google[K].ApiKey+"&v="+c:a;if(ib("msie")||ib("safari")||ib("konqueror"))g=g+"&nocache="+_json_cache_defeater_++;e.src=g;var i=function(){e.onload=f;e[ab][Xa](e);delete e};ba.product=="Gecko"?e.onload=i:e.onreadystatechange=function(a){a=(a?a:k[eb]).target?(a?a:k[eb]).target:(a?a:k[eb]).srcElement;if(a.readyState=="loaded"||
a.readyState=="complete")a.onreadystatechange=f,i()};d[s](e)}function mb(a,c){return function(){return c[$a](a,arguments)}}function S(a,c,d){return function(){return c[$a](a,d)}}function nb(a){for(;a[B];)a[Xa](a[B])}function ob(a,c){if(a)try{nb(a),a[s](c)}catch(d){}return c}function T(a,c){try{a[s](c)}catch(d){}return c}function pb(a){return m.createTextNode(a?a:"")}function U(a,c){var d=m[A]("div");a&&o(d,a);c&&r(d,c);return d}function qb(a,c){var d=m[A]("div");a&&T(d,pb(a));c&&r(d,c);return d}
function V(a){var c=m[A]("div");a&&r(c,a);return c}function rb(a,c){var d=m[A]("span");a&&T(d,pb(a));c&&r(d,c);return d}function sb(a,c,d){var e=m[A]("table");e[Fa]("cellSpacing",a?a:0);e[Fa]("cellPadding",c?c:0);d&&r(e,d);return e}function tb(a,c,d){(a=a.insertRow(-1))||alert(a);for(var e=0;e<c;e++)X(a,d);return a}function X(a,c){var d=a.insertCell(-1);c&&r(d,c);return d}function ub(a){var c=m[A]("td");a&&r(c,a);return c}
function vb(a,c,d,e){var g=m[A]("img");g.src=a;c&&ha(g,c);d&&qa(g,d);e&&r(g,e);return g}function wb(a,c,d,e,g){var i=m[A]("a");i.href=a;c&&(e?T(i,rb(c,e)):T(i,pb(c)));d&&ma(i,d);g&&ja(i,g);return i}function Y(a,c,d,e,g){var i=U(f,e),l=m[A]("a");l.href=a;o(l,c);e&&r(l,e);d&&ma(l,d);g&&ja(l,g);i[s](l);return i}function xb(a){var c=m[A]("form");a&&r(c,a);return c}function yb(a,c){var d=m[A]("input");ia(d,"submit");p(d,a);c&&r(d,c);return d}
function zb(a,c,d){var e=m[A]("input");e[Fa]("autoComplete","off");ia(e,"text");a==-1?Z(e,"util-css-expand"):e.size=a>0?a:10;c&&Z(e,c);d&&p(e,d);return e}function Ab(a,c,d,e){var g=m[A]("input");ia(g,"checkbox");g.name=a;p(g,c);e&&r(g,e);d&&ka(g,d);return g}function Z(a,c){var d;a:{if(!(a==f||a[Ma]==f))for(var d=a[Ma][Ra](" "),e=0;e<d[D];e++)if(d[e]==c){d=!0;break a}d=!1}d||(a.className+=" "+c)}
function $(a,c){if(a[Ma]!=f){for(var d=a[Ma][Ra](" "),e=[],g=!1,i=0;i<d[D];i++)d[i]!=c?d[i]&&e[sa](d[i]):g=!0;g&&r(a,e[cb](" "))}}var Bb="",Cb={Eh:{Jj:1,Nj:1,Wj:1,id:1,Xj:1,"in":1,Zj:1,ak:1,bk:1,dk:1,gk:1,pk:1,Fk:1,Jk:1,Kk:1,Pk:1,Qk:1,Sk:1},Kj:{Bj:1,Dj:1,Fj:1,Gj:1,Hj:1,Ij:1,Eh:1,Oj:1,"do":1,Qj:1,Rj:1,Sj:1,Tj:1,Uj:1,Vj:1,$j:1,hk:1,ik:1,jk:1,kk:1,lk:1,mk:1,nk:1,ok:1,rk:1,sk:1,tk:1,uk:1,vk:1,wk:1,Ak:1,Ck:1,Ek:1,Gk:1,Hk:1,Ik:1,Nk:1,Ok:1,Rk:1},qk:{Cj:1}};
function ib(a){if(a in Db)return Db[a];return Db[a]=ba.userAgent[db]()[Ba](a)!=-1}var Db={},jb={},Eb,Fb;k.zj&&(Eb=!0,k.XMLHttpRequest&&(Fb=!0));function Gb(a){this.cd=a+"branding";this.Lc=a+"branding-vertical";this.Yj=a+"branding-img";this.Mk=a+"branding-user-defined";this.Of=a+"branding-img-noclear";this.Dh=a+"branding-clickable";this.text=a+"branding-text"};var Hb=f,Ib=function(){if(Hb!=f)return Hb;var a=m[A]("div");ha(a[H],"1px");qa(a[H],"1px");a[H].border="1px solid black";a[H].padding="1px";a[H].visibility="hidden";m[Wa][s](a);var c=a[za];m[Wa][Xa](a);return Hb=c==5};function Kb(a){return da(a[w]("px",""))||0}
function Lb(a,c){typeof a=="string"&&(a=m[x](a));var d=m.defaultView||{},e=c?a.offsetHeight:a[za],g=c?["Top","Bottom"]:["Right","Left"],i,i=Ib()?["margin"]:["border","margin","padding"],l=i[D],q=g[D];if(d&&d[Ua])for(var u=d[Ua](a,!1),d=0;d<l;d++)for(var z=0;z<q;z++)e+=Kb(u.getPropertyValue([i[d],g[z][db]()][cb]("-")));else{u=a[Ya];if(!Ib())for(z=0;z<q;z++)e+=Kb(u[["border",g[z],"Width"][cb]("")]);for(d=0;d<l;d++)if(i[d]!="border")for(z=0;z<q;z++)e+=Kb(u[[i[d],g[z]][cb]("")])}return e};google[I].a=function(){this.pa=this.Lj=f;this.Hf=!0;this.U={width:100,height:75};this.ab=google[I].a.Cb;this.Yf=1;this.Z(google[I].a.ea);this.yf();this.gwsUrl=this.w=this.O=this.Bk=this.z=this.ck=this.gc=this.Ab=this.Dd=this.Ic=this.ld=this.jd=f;this.Ha=[];var a;if(typeof k==="object"&&k[Ta]&&k[Ta].hostname&&k[Ta].hostname!=""){if(Bb==""){var c=k[Ta].hostname[db]()[Ra](".");c[D]<2&&(Bb=".com");a=c.pop();c=c.pop();Bb=a[D]==2?Cb[c]&&Cb[c][a]==1?"."+c+"."+a:"."+a:".com"}a=Bb}else a=".com";this.Mf=a;
this.Tb=this.Kb=f};P("google.search.Search",google[I].a);google[I].a.$d=google[K][Ia];Q(google[I].a,"BASE",google[I].a.$d);google[I].a.th=/style=([^&]*)/;google[I].a.Ba="large";Q(google[I].a,"LARGE_RESULTSET",google[I].a.Ba);google[I].a.ea="small";Q(google[I].a,"SMALL_RESULTSET",google[I].a.ea);google[I].a.fb="filtered_cse";Q(google[I].a,"FILTERED_CSE_RESULTSET",google[I].a.fb);google[I].a.Sg=8;Q(google[I].a,"LARGE_RESULTS",google[I].a.Sg);google[I].a.oh=4;Q(google[I].a,"SMALL_RESULTS",google[I].a.oh);
google[I].a.Lg=10;Q(google[I].a,"FILTERED_CSE_RESULTS",google[I].a.Lg);google[I].a.Vg="_top";Q(google[I].a,"LINK_TARGET_TOP",google[I].a.Vg);google[I].a.Ug="_self";Q(google[I].a,"LINK_TARGET_SELF",google[I].a.Ug);google[I].a.Tg="_parent";Q(google[I].a,"LINK_TARGET_PARENT",google[I].a.Tg);google[I].a.Cb="_blank";Q(google[I].a,"LINK_TARGET_BLANK",google[I].a.Cb);google[I].a.Db="order-by-relevance";Q(google[I].a,"ORDER_BY_RELEVANCE",google[I].a.Db);google[I].a.Ca="order-by-date";
Q(google[I].a,"ORDER_BY_DATE",google[I].a.Ca);google[I].a.Le="order-by-ascending-date";Q(google[I].a,"ORDER_BY_ASCENDING_DATE",google[I].a.Le);google[I].a.hc="restrict-type";Q(google[I].a,"RESTRICT_TYPE",google[I].a.hc);google[I].a.ib="restrict-safesearch";Q(google[I].a,"RESTRICT_SAFESEARCH",google[I].a.ib);google[I].a.Rc="active";Q(google[I].a,"SAFESEARCH_STRICT",google[I].a.Rc);google[I].a.Qc="off";Q(google[I].a,"SAFESEARCH_OFF",google[I].a.Qc);google[I].a.Ye="moderate";
Q(google[I].a,"SAFESEARCH_MODERATE",google[I].a.Ye);google[I].a.hb="restrict-extended";Q(google[I].a,"RESTRICT_EXTENDED_ARGS",google[I].a.hb);google[I].a.qj=R;Q(google[I].a,"strings",google[I].a.qj);google[I].a.Zh=function(){if(google[I].LoadArgs){var a=fa(google[I].LoadArgs)[Ca](google[I].a.th);if(a&&a[1])return a[1]}return f};google[I].a[E].Ki=function(){var a=this.Fa+"?hl="+google[I][L]+"&source=uds";a+=this.w?this.w:"&q=";return this.Qa&&this.Qa!=""?this.Qa:a};
google[I].a[E].fj=function(a){this.O=a==f||a==""?f:a};Q(google[I].a[E],"setQueryAddition",google[I].a[E].fj);google[I].a[E].Ta=function(a,c,d){a=google[I].a.$d+this.Va+"?callback="+a+"&context="+c+"&rsz="+this.Ia+"&hl="+google[I][L];this.Cc&&(a+="&source="+h(this.Cc));this.Mf&&(a+="&gss="+this.Mf);google[I].JSHash&&(a+="&sig="+google[I].JSHash);d&&(a+="&start="+d);return a};google[I].a[E].lj=function(a){this.Cc=a};Q(google[I].a[E],"setSearcherSrc",google[I].a[E].lj);
google[I].a[E].ac=function(a){this.ab=a};Q(google[I].a[E],"setLinkTarget",google[I].a[E].ac);O=google[I].a[E];O.u=function(){return this.ab&&this.ab!=""?this.ab:f};O.rc=function(){if(this.jd==f)this.jd="gsc-"+this.z+"Result";return this.jd};O.Ea=function(){if(this.ld==f)this.ld="gs-"+this.z+"Result";return this.ld};O.ci=function(){if(this.Ic==f)this.Ic=R[this.z];return this.Ab?this.Ab:this.Ic};O.Yh=function(){if(this.Dd==f)this.Dd=R[this.z];return this.Ab?this.Ab:this.Dd};O.$h=function(){return this.Ia};
Q(google[I].a[E],"getResultSetSize",google[I].a[E].$h);google[I].a[E].Z=function(a){if(a>0&&a<=8)this.Ia=a;else switch(a){case google[I].a.Ba:this.Ia=google[I].a.Ba;break;default:case google[I].a.ea:this.Ia=google[I].a.ea}};Q(google[I].a[E],"setResultSetSize",google[I].a[E].Z);
pa(google[I].a[E],function(a){var c=(new Date)[C]();this.Ud=c%100==1?c:-1;c=this.ra(a);c+=this.Mb?"&"+this.Mb:"";k._googleudsextrastuff&&(c+=k._googleudsextrastuff);this.cursor=f;this.Uf=a;hb(c,google[I][Na]);if(this.Ha&&this.Ha[D]>0)for(c=0;c<this.Ha[D];c++)this.Ha[c][M](a)});Q(google[I].a[E],"execute",google[I].a[E][M]);google[I].a[E].Nf=function(a){if(this[F]&&a<this[F].pages[D])a=this.ra(this.Uf,b,b,this[F].pages[a].start),this.cursor=f,hb(a,google[I][Na])};Q(google[I].a[E],"gotoPage",google[I].a[E].Nf);
google[I].a[E].vh=function(a){this.Ha&&this.Ha[sa](a)};Q(google[I].a[E],"addRelatedSearcher",google[I].a[E].vh);google[I].a[E].Xh=function(a,c,d){return this.ra(a,c,d)+"&key="+google[K].ApiKey+"&v="+google[I][Na]};Q(google[I].a[E],"getExecuteUrl",google[I].a[E].Xh);google[I].a[E].Na=function(a){var c=Y("http://code.google.com/apis/ajaxsearch/faq.html",R.watermark+" - "+this.Fh(),"_blank","gs-watermark");T(a,c)};google[I].a[E].Fh=function(){var a=new Date;return a.getMonth()+1+"/"+a.getFullYear()};
google[I].a[E].sb=function(a){var c,c=a.getFullYear(),d=a.getMonth(),e=R["month-abbr"][d],a=a.getDate();a<10&&(a="0"+a);switch(google[I].ShortDatePattern){case "MDY":c=e+" "+a+", "+c;break;case "YMD":google[I][L]=="zh-CN"||google[I][L]=="zh-TW"||google[I][L]=="ja"||google[I][L]=="ko"?(e=Mb[google[I][L]],c=c+e.year+(d+1)+e.month+a+e.day):c=c+" "+e+" "+a;break;default:case "DMY":c=a+" "+e+" "+c}return c};Q(google[I].a[E],"formatToShortDate",google[I].a[E].sb);
var Mb={"zh-CN":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},"zh-TW":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},ja:{month:"\u6708",year:"\u5e74",day:"\u65e5"},ko:{month:" \uc6d4 ",year:" \ub144 ",day:" \uc77c "}};google[I].a.Je=36E5;google[I].a.gh=6E4;google[I].a.fh=864E5;
google[I].a[E].td=function(a){var c=(new Date)[C](),d=a[C]();if(c<d)return R["n-minutes-ago"](2);c-=d;if(c<google[I].a.Je)return a=n[xa](c/google[I].a.gh),R["n-minutes-ago"](a<=1?2:a);if(c<google[I].a.fh)return a=n[xa](c/google[I].a.Je),a<=1?R["one-hour-ago"]:R["n-hours-ago"](a);return this.sb(a)};Q(google[I].a[E],"formatToRelativeDate",google[I].a[E].td);google[I].a[E].yf=function(){this.yk=this.gwsUrl=f;this.results=[]};Q(google[I].a[E],"clearResults",google[I].a[E].yf);
google[I].a[E].Ph=function(){this.zf&&this.zf();if(this.Ud!=-1)google[K].recordStat("asa_"+this.z,"req."+((new Date)[C]()-this.Ud),!0),this.Ud=-1};
google[I].a[E].ca=function(a,c,d,e){this.gwsUrl=f;if(this.results&&this.results[D]>0)for(var g=0;g<this.results[D];g++)if(this.results[g].html){var i=this.results[g].html;Nb||(Nb=m[A]("DIV"));Nb[s](i);o(Nb,"")}a&&a.results&&a.results[D]>0?(this.results=a.results,a[F]&&a[F].moreResultsUrl?this.gwsUrl=this.Qa&&this.Qa!=""?this.Qa:a[F].moreResultsUrl:this.w&&this.Fa&&(this.gwsUrl=this.Ki())):this.results=[];this.completionStatus=c;this.hashStatus=e;this.Mj=d;this.fg=a&&a.resultAttribution&&a.resultAttribution!=
f&&a.resultAttribution!=""?a.resultAttribution:f;a&&a[F]&&a[F].pages&&a[F].pages[D]>0?this.cursor=a[F]:typeof this[F]!="undefined"&&delete this[F];a&&a.context?this.context=a.context:typeof this.context!="undefined"&&delete this.context;a&&a.promotions?this.promotions=a.promotions:typeof this.promotions!="undefined"&&delete this.promotions;a&&a.omittedResults?this.omittedResults=a.omittedResults:typeof this.omittedResults!="undefined"&&delete this.omittedResults;a&&a.spelling?this.spelling=a.spelling:
typeof this.spelling!="undefined"&&delete this.spelling;this.Hf&&this.yh();this.Ph()};Q(google[I].a[E],"onSearchComplete",google[I].a[E].ca);google[I].a[E].If=function(){var a=f;this.fg&&(a=U(this.fg,"gs-results-attribution"));return a};Q(google[I].a[E],"getAttribution",google[I].a[E].If);google[I].a[E].yh=function(){for(var a,c,a=0;a<this.results[D];a++)c=this.results[a],this.K(c)};google[I].a[E].yb=function(a,c,d){d||(d=[f]);this.zf=S(a,c,d)};Q(google[I].a[E],"setSearchCompleteCallback",google[I].a[E].yb);
google[I].a.ma=function(a,c){var d;if(a[D])for(var e=0;e<a[D];e++)if(a[e]==f){a[e]=c;d=e;break}d||(d=a[D],a[sa](c));return d};Q(google[I].a,"AllocateCompletionMapContext",google[I].a.ma);google[I].a[E].dc=function(a){this.Ab=a};Q(google[I].a[E],"setUserDefinedLabel",google[I].a[E].dc);google[I].a[E].nj=function(a){this.gc=a};Q(google[I].a[E],"setUserDefinedClassSuffix",google[I].a[E].nj);google[I].a[E].dj=function(){this.Hf=!1};Q(google[I].a[E],"setNoHtmlGeneration",google[I].a[E].dj);
google[I].a.xb=function(a,c,d,e,g){var i=n.min(n.min(d[v]/a,d[bb]/c),1),l={};ha(l,n[wa](a*i));qa(l,n[wa](c*i));if(e&&(ha(e,l[v]),qa(e,l[bb]),g))e[H].left=(d[v]-l[v])/2+"px";return l};Q(google[I].a,"scaleImage",google[I].a.xb);google[I].a.pf=1;Q(google[I].a,"VERTICAL_BRANDING",google[I].a.pf);google[I].a.Mg=2;Q(google[I].a,"HORIZONTAL_BRANDING",google[I].a.Mg);
google[I].a.Th=function(a,c,d){var e=c&&c==google[I].a.pf,g=new Gb("gsc-"),c=V(g.cd),i=sb(f,f,g.cd);T(c,i);e=!e;e||(Z(c,g.Lc),Z(i,g.Lc));var l=tb(i,0),q,u;e?u=q=l:(q=l,u=tb(i,0));var z="/css/small-logo.png",G=51,l=15;d&&typeof d=="string"&&d[Ca](/^http:\/\/www\.youtube\.com/)&&(z="/css/youtube-logo-55x24.png",G=55,l=24,Z(c,g.cd+"-youtube"),e||(Z(c,g.Lc+"-youtube"),Z(i,g.Lc+"-youtube")));e=X(q,g.text);i=X(u,g.Of);q=U(R["powered-by"],g.text);z=google[K][Ia]+z;u=g.Of;Eb&&!Fb?(u=V(u),u[H].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+
z+'")',ha(u[H],G+"px"),qa(u[H],l+"px")):u=vb(z,f,f,u);l=u;T(e,q);if(d){e="http://www.google.com";if(typeof d=="string"&&(d[Ca](/^http:\/\/[a-z]*\.google\.com/)||d[Ca](/^http:\/\/www\.youtube\.com/)))e=d;d=wb(e,f,"_BLANK");r(d,g.Dh);T(d,l);T(i,d)}else T(i,l);a&&(a=typeof a=="string"?m[x](a):a,nb(a),T(a,c));return c};Q(google[I].a,"getBranding",google[I].a.Th);google[I].a.setOnLoadCallback=function(a,c){google.setOnLoadCallback(a,c)};Q(google[I].a,"setOnLoadCallback",google[I].a.setOnLoadCallback);
var Nb;google[I].a[E].Rh=function(a){var c=this.Kb;a&&(c=a);var a={},d=V(this.Ea());Z(d,"gs-result");Z(d,"gs-error-result");c=U(c,"gs-snippet");T(d,c);a.html=d;return a};google[I].a[E].Sh=function(a){var c=this.Tb;a&&(c=a);var a={},d=V(this.Ea());Z(d,"gs-result");Z(d,"gs-no-results-result");c=U(c,"gs-snippet");T(d,c);a.html=d;return a};j("google.search.CurrentLocale",ea);j("google.search.ShortDatePattern",aa);google[I].r=function(){google[I].a[J](this);this.z="blog";this.Va="/GblogSearch";this.Fa="http://blogsearch.google.com/blogsearch";this.l=f;this.V=!1;this.ob=!0;this.pa=mb(this,google[I].r[E].Ga);this.nb="gsc-blogConfig";this.p=f};P("google.search.BlogSearch",google[I].r);gb(google[I].r,google[I].a);google[I].r.I="GblogSearch";Q(google[I].r,"RESULT_CLASS",google[I].r.I);google[I].r.o=[];google[I].r.M=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[I].r.o[i];google[I].r.o[i]=f;a.ca(c,d,e,g)};
Q(google[I].r,"RawCompletion",google[I].r.M);google[I].r[E].ra=function(a,c,d,e){d=d==f?google[I].a.ma(google[I].r.o,this):d;c=this.Ta(c==f?"google.search.BlogSearch.RawCompletion":c,d,e);this.O&&(a=a+" "+this.O);this.l&&(a=a+" blogurl:"+this.l);a="&q="+h(a);this.V&&(a+="&scoring=d");c+=a;this.w=a;return c};
google[I].r[E].K=function(a){a.html&&delete a.html;var c=V(this.Ea());Z(c,"gs-result");var d,d=Y(a.postUrl,a[La],this.u(),"gs-title");T(c,d);d=new Date(a.publishedDate);d=U(this.sb(d),"gs-publishedDate");T(c,d);d=new Date(a.publishedDate);d=U(this.td(d),"gs-relativePublishedDate");T(c,d);d=U(a[ya],"gs-snippet");T(c,d);d=Y(a.blogUrl,a.blogUrl,this.u(),"gs-visibleUrl");T(c,d);a.html=c;this.Na(a.html)};Q(google[I].r[E],"createResultHtml",google[I].r[E].K);
google[I].r[E].Ka=function(a){this.l=a==f||a==""?f:a};Q(google[I].r[E],"setSiteRestriction",google[I].r[E].Ka);google[I].r[E].R=function(a){this.V=a==google[I].a.Ca?!0:!1};Q(google[I].r[E],"setResultOrder",google[I].r[E].R);
google[I].r[E].Ga=function(a,c){if(c){if(this.p==f){var d=V("gsc-configSetting");this.p=Ab(f,"0",this.V,"gsc-configSettingCheckbox");T(d,this.p);T(d,U(R["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=V("gsc-configSettingSubmit");T(e,yb(R[Va],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.p,this.V);this.p[Da]()}else this.p&&(this.p[Oa]?this.R(google[I].a.Ca):this.R(google[I].a.Db))};google[I].m=function(){google[I].a[J](this);this.z="book";this.Va="/GbookSearch";this.Fa="http://books.google.com/books";this.qc=!1;this.Xd=f};P("google.search.BookSearch",google[I].m);gb(google[I].m,google[I].a);google[I].m.I="GbookSearch";Q(google[I].m,"RESULT_CLASS",google[I].m.I);google[I].m.of="user-list";Q(google[I].m,"USER_LIST",google[I].m.of);google[I].m.ff=1;Q(google[I].m,"TYPE_ALL_BOOKS",google[I].m.ff);google[I].m.kf=2;Q(google[I].m,"TYPE_FULL_VIEW_BOOKS",google[I].m.kf);
google[I].m.o=[];google[I].m.M=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[I].m.o[i];google[I].m.o[i]=f;a.ca(c,d,e,g)};Q(google[I].m,"RawCompletion",google[I].m.M);google[I].m[E].ra=function(a,c,d,e){d=d==f?google[I].a.ma(google[I].m.o,this):d;c=this.Ta(c==f?"google.search.BookSearch.RawCompletion":c,d,e);this.O&&(a=a+" "+this.O);a="&q="+h(a);this.qc&&(a+="&as_brr=1");this.Xd&&(a=a+"&as_list="+this.Xd);c+=a;this.w=a;return c};
google[I].m[E].K=function(a){a.html&&delete a.html;a.thumbnailHtml=this.kd(a);var c=V(this.Ea());Z(c,"gs-result");var d=V("gs-text-box"),e=sb(),g=tb(e,0),i=X(g,"gs-image-box"),g=X(g,"gs-text-box");T(i,a.thumbnailHtml[Ga](!0));T(g,d);T(c,e);e=Y(a.unescapedUrl,a[La],this.u(),"gs-title");T(d,e);e=U(R.by+"&nbsp;"+a.authors,"gs-author");T(d,e);e=V("gs-spacer");T(d,e);a.publishedYear&&(e=U(a.publishedYear,"gs-publishedDate"),T(d,e));ca(a.pageCount,10)>0&&(e=U("-&nbsp;"+R["page-count"](a.pageCount),"gs-pageCount"),
T(d,e));e=Y("http://books.google.com","books.google.com",this.u(),"gs-visibleUrl");T(d,e);a.html=c;this.Na(a.html)};Q(google[I].m[E],"createResultHtml",google[I].m[E].K);
google[I].m[E].kd=function(a){var c=V("gs-image-box gs-book-image-box"),d=V("gs-row-1"),e=vb("http://books.google.com/googlebooks/pages-trans.gif",f,f,"gs-pages");T(d,e);e=vb("http://books.google.com/googlebooks/p_edge-trans.gif",f,f,"gs-page-edge");T(d,e);T(c,d);d=V("gs-row-2");e=google[I].a.xb(a.tbWidth,a.tbHeight,this.U);e=vb(a.tbUrl,e[v],e[bb],"gs-image");a=wb(a.unescapedUrl,f,this.u(),"gs-image");r(a,"gs-image");T(a,e);T(d,a);T(c,d);return c};
google[I].m[E].Y=function(a,c){if(a==google[I].a.hc)c?c==google[I].m.ff?this.qc=!1:c==google[I].m.kf?this.qc=!0:this.Y(a,f):this.qc=!1;else if(a==google[I].m.of)this.Xd=c&&c[Ca](/^[a-zA-Z0-9\-_]*$/)?c:f};Q(google[I].m[E],"setRestriction",google[I].m[E].Y);google[I].c=function(){google[I].a[J](this);this.Yf=2;this.z="image";this.Va="/GimageSearch";this.Fa="http://images.google.com/images";this.l=this.Jd=this.sd=this.zd=this.xd=this.wd=this.yd=this.wa=f;this.U={width:112,height:84}};P("google.search.ImageSearch",google[I].c);gb(google[I].c,google[I].a);google[I].c.I="GimageSearch";Q(google[I].c,"RESULT_CLASS",google[I].c.I);google[I].c.Re="restrict-imagesize";Q(google[I].c,"RESTRICT_IMAGESIZE",google[I].c.Re);google[I].c.Qg=["icon"];
Q(google[I].c,"IMAGESIZE_SMALL",google[I].c.Qg);google[I].c.Pg=["small","medium","large","xlarge"];Q(google[I].c,"IMAGESIZE_MEDIUM",google[I].c.Pg);google[I].c.Og=["xxlarge"];Q(google[I].c,"IMAGESIZE_LARGE",google[I].c.Og);google[I].c.Ng=["huge"];Q(google[I].c,"IMAGESIZE_EXTRA_LARGE",google[I].c.Ng);google[I].c.Pe="restrict-coloration";Q(google[I].c,"RESTRICT_COLORIZATION",google[I].c.Pe);google[I].c.ae="mono";Q(google[I].c,"COLORIZATION_BLACK_AND_WHITE",google[I].c.ae);google[I].c.ce="gray";
Q(google[I].c,"COLORIZATION_GRAYSCALE",google[I].c.ce);google[I].c.be="color";Q(google[I].c,"COLORIZATION_COLOR",google[I].c.be);google[I].c.Oe="restrict-colorfilter";Q(google[I].c,"RESTRICT_COLORFILTER",google[I].c.Oe);google[I].c.le="red";Q(google[I].c,"COLOR_RED",google[I].c.le);google[I].c.ie="orange";Q(google[I].c,"COLOR_ORANGE",google[I].c.ie);google[I].c.oe="yellow";Q(google[I].c,"COLOR_YELLOW",google[I].c.oe);google[I].c.he="green";Q(google[I].c,"COLOR_GREEN",google[I].c.he);
google[I].c.me="teal";Q(google[I].c,"COLOR_TEAL",google[I].c.me);google[I].c.ee="blue";Q(google[I].c,"COLOR_BLUE",google[I].c.ee);google[I].c.ke="purple";Q(google[I].c,"COLOR_PURPLE",google[I].c.ke);google[I].c.je="pink";Q(google[I].c,"COLOR_PINK",google[I].c.je);google[I].c.ne="white";Q(google[I].c,"COLOR_WHITE",google[I].c.ne);google[I].c.ge="gray";Q(google[I].c,"COLOR_GRAY",google[I].c.ge);google[I].c.de="black";Q(google[I].c,"COLOR_BLACK",google[I].c.de);google[I].c.fe="brown";
Q(google[I].c,"COLOR_BROWN",google[I].c.fe);google[I].c.Qe="restrict-filetype";Q(google[I].c,"RESTRICT_FILETYPE",google[I].c.Qe);google[I].c.ve="jpg";Q(google[I].c,"FILETYPE_JPG",google[I].c.ve);google[I].c.we="png";Q(google[I].c,"FILETYPE_PNG",google[I].c.we);google[I].c.ue="gif";Q(google[I].c,"FILETYPE_GIF",google[I].c.ue);google[I].c.te="bmp";Q(google[I].c,"FILETYPE_BMP",google[I].c.te);google[I].c.Se="restrict-imagetype";Q(google[I].c,"RESTRICT_IMAGETYPE",google[I].c.Se);google[I].c.ye="face";
Q(google[I].c,"IMAGETYPE_FACES",google[I].c.ye);google[I].c.xe="clipart";Q(google[I].c,"IMAGETYPE_CLIPART",google[I].c.xe);google[I].c.ze="lineart";Q(google[I].c,"IMAGETYPE_LINEART",google[I].c.ze);google[I].c.Ae="news";Q(google[I].c,"IMAGETYPE_NEWS",google[I].c.Ae);google[I].c.Be="photo";Q(google[I].c,"IMAGETYPE_PHOTO",google[I].c.Be);google[I].c.Te="restrict-rights";Q(google[I].c,"RESTRICT_RIGHTS",google[I].c.Te);google[I].c.Xe="(cc_publicdomain|cc_attribute|cc_sharealike|cc_noncommercial|cc_nonderived)";
Q(google[I].c,"RIGHTS_REUSE",google[I].c.Xe);google[I].c.Ve="(cc_publicdomain|cc_attribute|cc_sharealike|cc_nonderived).-(cc_noncommercial)";Q(google[I].c,"RIGHTS_COMMERCIAL_REUSE",google[I].c.Ve);google[I].c.We="(cc_publicdomain|cc_attribute|cc_sharealike|cc_noncommercial).-(cc_nonderived)";Q(google[I].c,"RIGHTS_MODIFICATION",google[I].c.We);google[I].c.Ue="(cc_publicdomain|cc_attribute|cc_sharealike).-(cc_noncommercial|cc_nonderived)";Q(google[I].c,"RIGHTS_COMMERCIAL_MODIFICATION",google[I].c.Ue);
google[I].c.o=[];google[I].c.M=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[I].c.o[i];google[I].c.o[i]=f;a.ca(c,d,e,g)};Q(google[I].c,"RawCompletion",google[I].c.M);
google[I].c[E].ra=function(a,c,d,e){d=d==f?google[I].a.ma(google[I].c.o,this):d;c=this.Ta(c==f?"google.search.ImageSearch.RawCompletion":c,d,e);this.O&&(a=a+" "+this.O);a="&q="+h(a);this.wa&&(a=a+"&safe="+this.wa);this.yd&&(a=a+"&imgsz="+h(this.yd));this.wd&&(a=a+"&imgc="+h(this.wd));this.xd&&(a=a+"&imgcolor="+h(this.xd));this.zd&&(a=a+"&imgtype="+h(this.zd));this.sd&&(a=a+"&as_filetype="+h(this.sd));this.Jd&&(a=a+"&as_rights="+h(this.Jd));this.l&&(a=a+"&as_sitesearch="+h(this.l));c+=a;this.w=a;if(e&&
e!=0)this.w=this.w+"&start="+e;return c};
google[I].c[E].K=function(a){a.html&&delete a.html;var c=V(this.Ea());Z(c,"gs-result");var d=V("gs-image-box"),e=google[I].a.xb(a.tbWidth,a.tbHeight,this.U),g=vb(a.tbUrl,e[v],e[bb],"gs-image");g[H].left=(this.U[v]-e[v])/2+"px";ja(g,a.titleNoFormatting+" ("+a.visibleUrl+")");e=wb(a.unescapedUrl,f,this.u(),"gs-image");r(e,"gs-image");T(e,g);T(d,e);T(c,d);d=V("gs-text-box");g=U(a[ya],"gs-snippet");ja(g,a.contentNoFormatting);T(d,g);g=U(a[v]+" x "+a[bb],"gs-size");T(d,g);g=Y(a.originalContextUrl,a.visibleUrl,
this.u(),"gs-visibleUrl");ja(g,a.visibleUrl);T(d,g);T(c,d);a.html=c;this.Na(a.html)};Q(google[I].c[E],"createResultHtml",google[I].c[E].K);google[I].c[E].Ka=function(a){this.l=a};Q(google[I].c[E],"setSiteRestriction",google[I].c[E].Ka);
google[I].c[E].Y=function(a,c){if(a==google[I].a.ib)this.wa=c?c==google[I].a.Rc||c==google[I].a.Qc?c:f:f;else if(a==google[I].c.Re)this.yd=c?c[cb]("|"):f;else if(a==google[I].c.Pe)this.wd=c?c==google[I].c.ae||c==google[I].c.ce||c==google[I].c.be?c:f:f;else if(a==google[I].c.Oe)this.xd=c?c==google[I].c.le||c==google[I].c.ie||c==google[I].c.oe||c==google[I].c.he||c==google[I].c.me||c==google[I].c.ee||c==google[I].c.ke||c==google[I].c.je||c==google[I].c.ne||c==google[I].c.ge||c==google[I].c.de||c==google[I].c.fe?
c:f:f;else if(a==google[I].c.Qe)this.sd=c?c==google[I].c.ve||c==google[I].c.we||c==google[I].c.ue||c==google[I].c.te?c:f:f;else if(a==google[I].c.Se)this.zd=c?c==google[I].c.ye||c==google[I].c.xe||c==google[I].c.ze||c==google[I].c.Ae||c==google[I].c.Be?c:f:f;else if(a==google[I].c.Te)this.Jd=c?c==google[I].c.Xe||c==google[I].c.Ve||c==google[I].c.We||c==google[I].c.Ue?c:f:f};Q(google[I].c[E],"setRestriction",google[I].c[E].Y);google[I].f=function(){google[I].a[J](this);this.ka=f;this.ha="San Francisco, CA";this.oa={y:37.77916,x:-122.42009};this.lb=f;this.Sb=!0;this.Eb=!1;this.ub=f;this.ob=!0;this.pa=mb(this,this.Ga);this.nb="gsc-locationConfig";this.z="local";this.Va="/GlocalSearch";this.Fa="http://www.google.com/local";this.kb=this.N=f};P("google.search.LocalSearch",google[I].f);gb(google[I].f,google[I].a);google[I].f.I="GlocalSearch";Q(google[I].f,"RESULT_CLASS",google[I].f.I);google[I].f.jf="blended";
Q(google[I].f,"TYPE_BLENDED_RESULTS",google[I].f.jf);google[I].f.mf="kmlonly";Q(google[I].f,"TYPE_KMLONLY_RESULTS",google[I].f.mf);google[I].f.nf="localonly";Q(google[I].f,"TYPE_LOCALONLY_RESULTS",google[I].f.nf);google[I].f.Yd="disabled";Q(google[I].f,"ADDRESS_LOOKUP_DISABLED",google[I].f.Yd);google[I].f.Zd="enabled";Q(google[I].f,"ADDRESS_LOOKUP_ENABLED",google[I].f.Zd);google[I].f.bf=0;Q(google[I].f,"STATIC_MAP_ZOOM_FARTHEST",google[I].f.bf);google[I].f.sh=13;
Q(google[I].f,"STATIC_MAP_ZOOM_DEFAULT",google[I].f.sh);google[I].f.af=21;Q(google[I].f,"STATIC_MAP_ZOOM_CLOSEST",google[I].f.af);google[I].f.Yc=8;Q(google[I].f,"STATIC_MAP_MAX_POINTS",google[I].f.Yc);google[I].f.Hi=3.141592653589;google[I].f.Mh=6367E3;google[I].f.uj=16093;google[I].f.o=[];google[I].f.M=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[I].f.o[i];google[I].f.o[i]=f;a.resultViewport=c&&c.viewport?c.viewport:f;a.ca(c,d,e,g)};Q(google[I].f,"RawCompletion",google[I].f.M);
google[I].f[E].ra=function(a,c,d,e){d=d==f?google[I].a.ma(google[I].f.o,this):d;c=this.Ta(c==f?"google.search.LocalSearch.RawCompletion":c,d,e);e="";e="&q="+h(a);c+=e;this.viewport=f;if(this.ka){var g;this.Sb?(d=this.ka.getCenterLatLng(),g=this.ka.getSpanLatLng(),a="&sll="+d.y+","+d.x,a+="&sspn="+g[bb]+","+g[v]):(d=this.ka.getCenter(),g=this.ka.getBounds().toSpan().toUrlValue(),a="&sll="+d.y+","+d.x,a+="&sspn="+g);a+=google[I].f.dd(d.y,d.x);c+=a;e+=a}else this.oa?(a="&sll="+this.oa.y+","+this.oa.x,
this.lb&&(a=a+"&sspn="+this.lb.lat+","+this.lb.lng),a+=google[I].f.dd(this.oa.y,this.oa.x),c+=a,e+=a):this.ha&&(a="&near="+h(this.ha),c+=a,e+=a);this.Eb&&(c+="&nogeocode=t",e+="&nogeocode=t");this.ub&&(c+="&mrt="+h(this.ub),e+="&mrt="+h(this.ub));if(e)this.w=e;return c};google[I].f.dd=function(a,c){var d=2*google[I].f.uj/google[I].f.Mh*2*google[I].f.Hi;return"&gll="+n[xa]((a-d)*1E6)+","+n[xa]((c-d)*1E6)+","+n[xa]((a+d)*1E6)+","+n[xa]((c+d)*1E6)+"&llsep=500,500"};Q(google[I].f,"centerToGll",google[I].f.dd);
google[I].f[E].K=function(a){a.html&&delete a.html;var c=V(this.Ea());Z(c,"gs-result");var d,d=Y(a.url,a[La],this.u(),"gs-title");T(c,d);a.listingType=="kml"&&a[ya]&&a[ya]!=""&&(d=U(a[ya],"gs-snippet"),T(c,d));var e=V("gs-address");if(a.addressLines&&a.addressLines[D]>0)for(var g=0;g<a.addressLines[D];g++){var d=a.addressLines[g],i="gs-addressLine";g==0?i="gs-street gs-addressLine":g==1&&(i="gs-city gs-addressLine");d=U(d,i);T(e,d)}else{d=U(a.streetAddress,"gs-street");T(e,d);g="";if(a.city!="")g=
a.city,a.region!=""&&(g+=", ");d=U(g,"gs-city");T(e,d);d=U(a.region,"gs-region");T(e,d)}d=U(a.country,"gs-country");T(e,d);T(c,e);if(a.phoneNumbers&&a.phoneNumbers[D]){for(var g=e=f,d=a.phoneNumbers[0],l=0;l<a.phoneNumbers[D];l++){i=a.phoneNumbers[l];if(i[Ha]=="main"){e=i;break}if(i[Ha]==""||i[Ha]=="mobile"&&g==f)g=i}d=U((e?e:g?g:d).number,"gs-phone");T(c,d)}a.ddUrl&&a.ddUrl!=""&&(d=Y(a.ddUrl,R.directions,this.u(),"gs-directions"),T(c,d));a.ddUrlToHere&&a.ddUrlToHere!=""&&a.ddUrlFromHere&&a.ddUrlFromHere!=
""&&(d=V("gs-directions-to-from"),e=U(R["get-directions"]+":","gs-label"),d[s](e),e=Y(a.ddUrlToHere,R["to-here"],this.u(),"gs-secondary-link"),d[s](e),e=U("-","gs-spacer"),d[s](e),e=Y(a.ddUrlFromHere,R["from-here"],this.u(),"gs-secondary-link"),d[s](e),T(c,d));a.html=c;this.Na(a.html)};Q(google[I].f[E],"createResultHtml",google[I].f[E].K);
google[I].f[E].mg=function(a){if(a.centerAndZoom){if(this.Sb=!0,this.ka=a,this.oa=f,this.ha="",this.N)this.N=f}else if(a.setCenter){if(this.Sb=!1,this.ka=a,this.lb=this.oa=f,this.ha="",this.N)this.N=f}else if(a.x&&a.y){if(this.Sb=!0,this.oa=a,this.ka=this.lb=f,this.ha="",this.N)this.N=f}else if(a!=f&&a!=""){this.Sb=!0;this.ka=f;this.ha=a;this.oa=f;if(this.N)this.N=f;var c=new google[I].f;c.yb(this,this.xh,[c,a]);c[M](a)}};Q(google[I].f[E],"setCenterPoint",google[I].f[E].mg);
google[I].f[E].xh=function(a,c){if(a.results&&a.results[D]){var d={};d.y=da(a.results[0].lat);d.x=da(a.results[0].lng);this.oa=d;this.ha=c;this.ob=!0;this.ka=f;if(a.resultViewport)d={},d.ek=da(a.resultViewport.span.lat)/2,d.fk=da(a.resultViewport.span.lng)/2,this.lb=d}};
google[I].f[E].Ga=function(a,c){if(c){if(this.N==f){var d=f;if(this.ka==f){var e=V("gsc-configSetting");this.N=zb(f,"gsc-configSettingInput",this.ha==""?f:this.ha);T(e,U(R["search-location"],"gsc-configSettingInputLabel"));T(e,this.N);T(a,e);d=this.N}e=V("gsc-configSetting");this.kb=Ab(f,"0",this.Eb,"gsc-configSettingCheckbox");T(e,this.kb);T(e,U(R["disable-address-lookup"],"gsc-configSettingCheckboxLabel"));if(d==f)d=this.kb;var g=U(f,"gsc-configSettingSubmit");T(g,yb(R[Va],"gsc-configSettingSubmit"));
T(e,g);T(a,e);d[Da]()}}else{if(this.N){if(this.N[y])this.ha=this.N[y],this.mg(this.ha);this.N=f}if(this.kb)this.Eb=this.kb[Oa],this.kb=f;nb(a)}};google[I].f[E].Xi=function(a){if(a==google[I].f.Yd)this.Eb=!0;else if(a==google[I].f.Zd)this.Eb=!1};Q(google[I].f[E],"setAddressLookupMode",google[I].f[E].Xi);google[I].f.eg=function(a,c,d,e){var g=a.staticMapUrl,g=g[w](/&size=\d*x\d*/,"&size="+d+"x"+c);e&&e<=google[I].f.af&&e>=google[I].f.bf&&(g=g[w](/&zoom=\d*/,"&zoom="+e));return a.staticMapUrl=g};
Q(google[I].f,"resizeStaticMapUrl",google[I].f.eg);
google[I].f.Gh=function(a,c,d,e){var g="",i={staticMapUrl:"http://maps.google.com/maps/api/staticmap?maptype=roadmap&size=150x100&zoom=13&format=gif&sensor=false"},c=google[I].f.eg(i,c,d,e);e==f&&(c=c[w](/&zoom=\d*/,""));e=a[D];if(e>google[I].f.Yc)e=google[I].f.Yc;for(d=0;d<e;d++){var l,l=a[d];if(l.lat&&l.lng)typeof l.lat=="string"?(i=da(l.lat),l=da(l.lng)):(i=l.lat,l=l.lng);else if(l.x&&l.y)i=l.y,l=l.x;else return f;i="&markers=__ICONID____LAT__,__LNG__"[w](/__LAT__/,i);i=i[w](/__LNG__/,l);l=65+
d;i=e>1?i[w](/__ICONID__/,"label:"+String.fromCharCode(l)+"|"):i[w](/__ICONID__/,"");g+=i}return c+g};Q(google[I].f,"computeStaticMapUrl",google[I].f.Gh);google[I].f[E].Y=function(a,c){if(a==google[I].a.hc)c?(this.ub=f,this.ub=c==google[I].f.jf||c==google[I].f.mf||c==google[I].f.nf?c:f):this.ub=f};Q(google[I].f[E],"setRestriction",google[I].f[E].Y);google[I].n=function(){google[I].a[J](this);this.z="news";this.Va="/GnewsSearch";this.Fa="http://news.google.com/nwshp";this.Dk=f;this.zb="site:";this.V=!1;this.ob=!0;this.pa=mb(this,this.Ga);this.nb="gsc-newsConfig";this.H=this.p=f};P("google.search.NewsSearch",google[I].n);gb(google[I].n,google[I].a);google[I].n.I="GnewsSearch";Q(google[I].n,"RESULT_CLASS",google[I].n.I);google[I].n.Me="GnewsSearch.quote";Q(google[I].n,"QUOTE_RESULT_CLASS",google[I].n.Me);google[I].n.o=[];
google[I].n.M=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[I].n.o[i];google[I].n.o[i]=f;a.ca(c,d,e,g)};Q(google[I].n,"RawCompletion",google[I].n.M);
google[I].n[E].ra=function(a,c,d,e){d=d==f?google[I].a.ma(google[I].n.o,this):d;c=this.Ta(c==f?"google.search.NewsSearch.RawCompletion":c,d,e);d=f;a&&(d=a);this.O&&(d=d==f?this.O:d+" "+this.O);this.l&&(d=d==f?this.zb+this.l:d+" "+this.zb+this.l);a=d?"&q="+h(d):"";this.V&&(a+="&scoring=d");if(this.H){var d="",g;for(g in this.H)g.charAt(0)==":"&&(d+="&"+this.H[g]);a+=d}this.l&&this.zb=="source:"&&(c=c[w](/&hl=.*&/,"&hl=en&"));c+=a;this.w=a;if(e&&e!=0)this.w=this.w+"&start="+e;return c};
google[I].n[E].K=function(a){a.html&&delete a.html;if(a.GsearchResultClass!=google[I].n.Me){var c=V(this.Ea());Z(c,"gs-result");var d,d=Y(a.unescapedUrl,a[La],this.u(),"gs-title");T(c,d);d=U(a.publisher,"gs-publisher");T(c,d);d=a[Ta][Ra](",");d[D]>1&&(d=U(", "+d[d[D]-1],"gs-location"),T(c,d));d=new Date(a.publishedDate);d=U(" - "+this.sb(d),"gs-publishedDate");T(c,d);d=new Date(a.publishedDate);d=U(" - "+this.td(d),"gs-relativePublishedDate");T(c,d);d=U(a[ya],"gs-snippet");T(c,d);a.clusterUrl&&a.clusterUrl!=
""&&(d=Y(a.clusterUrl,R["related-articles"]+"&nbsp;&raquo;",this.u(),"gs-clusterUrl"),T(c,d));a.html=c;this.Na(a.html)}};Q(google[I].n[E],"createResultHtml",google[I].n[E].K);google[I].n[E].Ka=function(a){a==f||a==""?(this.l=f,this.zb="site:"):a[Ca]("[./:]")?(this.zb="site:",this.l=a):(this.zb="source:",this.l=a[w](/\s/g,"_"))};Q(google[I].n[E],"setSiteRestriction",google[I].n[E].Ka);google[I].n[E].R=function(a){this.V=a==google[I].a.Ca?!0:!1};Q(google[I].n[E],"setResultOrder",google[I].n[E].R);
google[I].n[E].Ga=function(a,c){if(c){if(this.p==f){var d=V("gsc-configSetting");this.p=Ab(f,"0",this.V,"gsc-configSettingCheckbox");T(d,this.p);T(d,U(R["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=V("gsc-configSettingSubmit");T(e,yb(R[Va],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.p,this.V);this.p[Da]()}else this.p&&(this.p[Oa]?this.R(google[I].a.Ca):this.R(google[I].a.Db))};
google[I].n[E].Ah={geo:!0,qsid:!0,quotesearch:!0,topic:!0,ned:!0,scoring:!0,as_mind:!0,as_minm:!0,as_miny:!0,as_maxd:!0,as_maxm:!0,as_maxy:!0};google[I].n[E].Y=function(a,c){if(a==google[I].a.hb)if(c)for(var d in c){var e=c[d];if(typeof this.Ah[d]!="undefined")this.H=this.H||{},this.H[":"+d]=d+"="+h(e)}else this.H=f};Q(google[I].n[E],"setRestriction",google[I].n[E].Y);google[I].j=function(){google[I].a[J](this);this.z="patent";this.Va="/GpatentSearch";this.Fa="http://www.google.com/patents";this.ug="";this.Yb=f;this.ob=!0;this.pa=mb(this,this.Ga);this.nb="gsc-patentConfig";this.p=f};P("google.search.PatentSearch",google[I].j);gb(google[I].j,google[I].a);google[I].j.I="GpatentSearch";Q(google[I].j,"RESULT_CLASS",google[I].j.I);google[I].j.gf=1;Q(google[I].j,"TYPE_ANY_STATUS",google[I].j.gf);google[I].j.lf=2;Q(google[I].j,"TYPE_ISSUED_PATENTS",google[I].j.lf);
google[I].j.hf=3;Q(google[I].j,"TYPE_APPLICATIONS",google[I].j.hf);google[I].j.o=[];google[I].j.M=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[I].j.o[i];google[I].j.o[i]=f;a.ca(c,d,e,g)};Q(google[I].j,"RawCompletion",google[I].j.M);google[I].j[E].ra=function(a,c,d,e){d=d==f?google[I].a.ma(google[I].j.o,this):d;c=this.Ta(c==f?"google.search.PatentSearch.RawCompletion":c,d,e);this.O&&(a=a+" "+this.O);a="&q="+h(a)+this.ug;this.Yb&&(a+=this.Yb);c+=a;this.w=a;return c};
google[I].j[E].K=function(a){a.html&&delete a.html;a.thumbnailHtml=this.kd(a);var c=V(this.Ea());Z(c,"gs-result");var d=V("gs-text-box"),e=sb(),g=tb(e,0),i=X(g,"gs-image-box"),g=X(g,"gs-text-box");T(i,a.thumbnailHtml[Ga](!0));T(g,d);T(c,e);i=Y(a.unescapedUrl,a[La],this.u(),"gs-title");T(d,i);e=V("gs-patent-info gs-metadata");T(d,e);i=f;i=a.patentNumber?a.patentStatus=="issued"?R["us-pat"]+"&nbsp;"+a.patentNumber:R["us-pat-app"]+"&nbsp;"+a.patentNumber:R["us-pat-app"]+"&nbsp; N/A";i=U(i,"gs-patent-number");
T(e,i);a.applicationDate&&(i=U(" - "+this.sb(new Date(a.applicationDate)),"gs-publishedDate"),T(e,i));a.assignee&&(i=U(" - "+a.assignee,"gs-author"),T(e,i));i=U(a[ya],"gs-snippet");T(d,i);T(d,i);a.html=c;this.Na(a.html)};Q(google[I].j[E],"createResultHtml",google[I].j[E].K);google[I].j[E].kd=function(a){var c=V("gs-patent-image"),d=vb(a.tbUrl,75,100,"gs-image"),a=wb(a.unescapedUrl,f,this.u(),"gs-image");r(a,"gs-image");T(a,d);T(c,a);return c};
google[I].j[E].R=function(a){this.Yb=a==google[I].a.Ca?"&scoring=d":a==google[I].a.Le?"&scoring=ad":f};Q(google[I].j[E],"setResultOrder",google[I].j[E].R);google[I].j[E].Y=function(a,c){if(a==google[I].a.hc)this.ug=c?c==google[I].j.gf?"":c==google[I].j.lf?"&as_psrg=1":c==google[I].j.hf?"&as_psra=1":"":""};Q(google[I].j[E],"setRestriction",google[I].j[E].Y);
google[I].j[E].Ga=function(a,c){if(c){var d=!1;this.Yb&&this.Yb=="&scoring=d"&&(d=!0);if(this.p==f){var e=V("gsc-configSetting");this.p=Ab(f,"0",d,"gsc-configSettingCheckbox");T(e,this.p);T(e,U(R["sort-by-date"],"gsc-configSettingCheckboxLabel"));d=V("gsc-configSettingSubmit");T(d,yb(R[Va],"gsc-configSettingSubmit"));T(e,d);T(a,e)}else ka(this.p,d);this.p[Da]()}else this.p&&(this.p[Oa]?this.R(google[I].a.Ca):this.R(google[I].a.Db))};google[I].D=function(){this.$f=this.ga=google[I].b.Xa;ra(this,f);this.U={width:112,height:84};this.Mc={width:100,height:75};this.Tb=f};P("google.search.SearcherOptions",google[I].D);google[I].D[E].og=function(a){switch(a){case google[I].b.se:case google[I].b.eb:case google[I].b.Xa:this.ga=a;break;default:this.ga=google[I].b.Xa}this.$f=this.ga};Q(google[I].D[E],"setExpandMode",google[I].D[E].og);google[I].D[E].gj=function(a){nb(a);ra(this,a)};Q(google[I].D[E],"setRoot",google[I].D[E].gj);
google[I].D[E].bc=function(a){this.Tb=a};Q(google[I].D[E],"setNoResultsString",google[I].D[E].bc);google[I].D[E].bj=function(a){a>100&&(a=100);qa(this.U,a);ha(this.U,n[wa](a*1.33))};Q(google[I].D[E],"setImageResultsTbHeight",google[I].D[E].bj);google[I].D[E].oj=function(a){a>100&&(a=100);qa(this.Mc,a);ha(this.Mc,n[wa](a*1.33))};Q(google[I].D[E],"setVideoResultsTbHeight",google[I].D[E].oj);google[I].A=function(){ga(this,f);this.sg=f;this.T=google[I].b.Ma;this.wf=!1;this.W=f};
P("google.search.DrawOptions",google[I].A);google[I].A[E].pg=function(a){ga(this,a)};Q(google[I].A[E],"setInput",google[I].A[E].pg);google[I].A[E].jj=function(a){a&&typeof a=="string"&&(a=m[x](a));this.sg=a};Q(google[I].A[E],"setSearchFormRoot",google[I].A[E].jj);google[I].A[E].ng=function(a){this.T=a==google[I].b.Ma||a==google[I].b.Aa?a:google[I].b.Ma};Q(google[I].A[E],"setDrawMode",google[I].A[E].ng);google[I].A[E].Zi=function(a){this.wf=a};Q(google[I].A[E],"setAutoComplete",google[I].A[E].Zi);
google[I].A[E].Nh=function(a,c,d){this.W={};this.W.gg=a;this.W.Li=c||"q";this.W.mi=d||!1};Q(google[I].A[E],"enableSearchboxOnly",google[I].A[E].Nh);
google[I].C=function(a,c,d){this.v=d;this.hd=this.rd=!1;this.h=a;this.G=f;this.Si=S(c,google[I].b[E].Ei,[this]);this.Wi=S(c,google[I].b[E].Fd,[this,google[I].C.Vc]);this.Vi=S(c,google[I].b[E].Fd,[this,google[I].C.Uc]);this.Ti=S(c,google[I].b[E].Fd,[this,google[I].C.$e]);this.Ri=S(c,google[I].b[E].Di,[this]);this.Qi=S(c,google[I].b[E].ri,[this]);this.h.yb(c,google[I].b[E].ca,[this]);this.h.Z(c.Wb);this.h.ac(c.ab);ra(this,f);this.X=this.pb=this.Pa=this.Id=this.Nb=this.Kc=f;this.Qb=!0};
google[I].C.Tc=0;google[I].C.Vc=1;google[I].C.Uc=2;google[I].C.$e=3;google[I].C[E].Nd=function(a){var c="gsc-results-selector ";c+=a==google[I].C.Tc?this.v.ga==google[I].b.Xa?"gsc-one-result-active":this.h.Ia==google[I].a.ea?"gsc-more-results-active":"gsc-all-results-active":a==google[I].C.Vc?"gsc-one-result-active":a==google[I].C.Uc?"gsc-more-results-active":"gsc-all-results-active";r(this.Id,c)};
google[I].b=function(a){if(!google[K].KeyVerified)if(google[I].b.Tf())google[K].KeyVerified=!0;else return;this.uf=this.Wb=google[I].a.ea;this.T=google[I].b.Ma;ra(this,f);this.Ac=f;ga(this,f);this.Jc=google[I].b.ic;this.hi=S(this,google[I].b[E].ti,[f]);this.ii=S(this,google[I].b[E].ui,[f]);this.tb=this.Zb=this.Kd=this.uc=f;this.Fb=this.li=!1;this.ab=google[I].a.Cb;this.Ad=R.copy;this.e=[];this.Ej=[];var c;if(a)for(var d=0;d<a[D];d++)c=new google[I].C(a[d],this,!1),this.e[sa](c)};
P("google.search.SearchControl",google[I].b);google[I].b[E].Gd=!1;google[I].b.Ke=R["no-results"];Q(google[I].b,"NO_RESULTS_DEFAULT_STRING",google[I].b.Ke);google[I].b.ef=350;Q(google[I].b,"TIMEOUT_SHORT",google[I].b.ef);google[I].b.ic=500;Q(google[I].b,"TIMEOUT_MEDIUM",google[I].b.ic);google[I].b.df=700;Q(google[I].b,"TIMEOUT_LONG",google[I].b.df);google[I].b.se=1;Q(google[I].b,"EXPAND_MODE_CLOSED",google[I].b.se);google[I].b.eb=2;Q(google[I].b,"EXPAND_MODE_OPEN",google[I].b.eb);google[I].b.Xa=3;
Q(google[I].b,"EXPAND_MODE_PARTIAL",google[I].b.Xa);google[I].b.Ma=1;Q(google[I].b,"DRAW_MODE_LINEAR",google[I].b.Ma);google[I].b.Aa=2;Q(google[I].b,"DRAW_MODE_TABBED",google[I].b.Aa);google[I].b.Ie="save";Q(google[I].b,"KEEP_LABEL_SAVE",google[I].b.Ie);google[I].b.He="keep";Q(google[I].b,"KEEP_LABEL_KEEP",google[I].b.He);google[I].b.Ge="include";Q(google[I].b,"KEEP_LABEL_INCLUDE",google[I].b.Ge);google[I].b.Fe="copy";Q(google[I].b,"KEEP_LABEL_COPY",google[I].b.Fe);google[I].b.Ee="blank";
Q(google[I].b,"KEEP_LABEL_BLANK",google[I].b.Ee);var Ob=google[K][Za].BUBBLEGUM,Pb=google[K][Za].GREENSKY,Qb=google[K][Za].ESPRESSO,Rb=google[K][Za].SHINY,Sb=google[K][Za].MINIMALIST;google[I].b.Wa={};google[I].b.Wa[Ob]={colorBackground:"#FDE5FF",colorTitleLink:"#0568CD",colorText:"#000",colorDomainLink:"#CC7A9F",fontFamily:"Arial"};
google[I].b.Wa[Pb]={colorBackground:"#EEFFE5",colorBorder:"#A9DA92",colorTitleLink:"#06C",colorText:"#454545",colorDomainLink:"#8D5FA7",fontFamily:"Trebuchet MS",fontSizeTitle:"14",fontSizeDescription:"14"};google[I].b.Wa[Qb]={colorBackground:"#F2F0E6",colorTitleLink:"#950000",colorText:"#333",colorDomainLink:"#A25B08",fontFamily:"Georgia",fontSizeTitle:"14",fontSizeDescription:"14",fontSizeDomainLink:"12"};
google[I].b.Wa[Rb]={colorBackground:"#F0F0F6",colorBorder:"#CCC",colorTitleLink:"#06C",colorDomainLink:"#008000",fontFamily:"Verdana"};google[I].b.Wa[Sb]={colorBackground:"#EEE",colorBorder:"#CCC",colorTitleLink:"#000",colorText:"#444",colorDomainLink:"#333",fontFamily:"Arial"};google[I].b.Pc="gsc-loading-id";try{google[I].b.appPath=k[Ta].href}catch(Ub){google[I].b.appPath=f}
google[I].b.Tf=function(){var a;a=k[Ta].host[db]()[Ra](".");if(a[D]<2)a=!1;else{var c=a.pop(),d=a.pop();(d=="igoogle"||d=="gmodules"||d=="googlesyndication")&&c=="com"?a=!0:(c[D]==2&&a[D]>0&&Cb[d]&&Cb[d][c]==1&&(d=a.pop()),a=d=="google")}if(a)return!0;google[K].KeyVerified=!0;google[K].LoadFailure=!1;return!0};Q(google[I].b,"keyCheck",google[I].b.Tf);google[I].b[E].zh=function(){var a=this;return function(){if(a.Gd)a.dg(),a.Gd=!1}};
google[I].b[E].Ib=function(a,c){google.load("ads.search","2",{callback:this.zh()});this.Oa=!0;this.Za=a;if(c){if(c.includeVerticalAds!=b)this.ya=c.includeVerticalAds;if(c.includeSideAds!=b)this.ya=c.includeSideAds;if(c.iframes!=b)this.Lb=c.iframes;if(c.useNarrowTopAd!=b&&this.Lb)this.Lk=c.useNarrowTopAd;if(c.channel)this.rf=c.channel;if(c.clientIP)this.sf=c.clientIP;if(c.safe)this.Zc=c.safe;if(c.userAgent)this.vf=c.userAgent;var d=c.adtest||c.debug;if(d)this.$c=d;if(c.numTopAds!=b)this.ua=c.numTopAds,
this.ua=n.max(0,n.min(4,this.ua));if(c.numSideAds!=b)this.ia=c.numSideAds,this.ya=(this.ia=n.max(0,n.min(8,this.ia)))?!0:!1;this.kg=c.enableSearchCompleteCallback?!0:!1}};Q(google[I].b[E],"enableAds",google[I].b[E].Ib);google[I].b[E].jb=function(a,c){c||(c=new google[I].D);a.Ha=f;this.e[sa](new google[I].C(a,this,c));if(this.Bc(a))this.di=!0;a.Cc="gsc"};Q(google[I].b[E],"addSearcher",google[I].b[E].jb);
google[I].b[E].Df=function(a){this.e[a].v[N]?(this.e[a].Qb=!1,ra(this.e[a],this.e[a].v[N]),Z(this.e[a][N],"gsc-resultsRoot"),$(this.e[a][N],"gsc-resultsbox-visible"),Z(this.e[a][N],"gsc-resultsbox-invisible")):ra(this.e[a],V("gsc-resultsRoot"));this.e[a].h.gc&&Z(this.e[a][N],"gsc-resultsRoot-"+this.e[a].h.gc);if(this.T==google[I].b.Aa)this.k[a].L=this.e[a][N];var c=sb(f,f,"gsc-resultsHeader"),d=tb(c,0);this.e[a].cb=X(d,"gsc-twiddleRegionCell");d=X(d,"gsc-configLabelCell");this.e[a].Kc=U("","gsc-twiddle");
T(this.e[a].cb,this.e[a].Kc);var e=qb(this.e[a].h.Yh(),"gsc-title");T(this.e[a].Kc,e);this.e[a].Nb=U("","gsc-stats");T(this.e[a].cb,this.e[a].Nb);var e=U(),g=U(R.blank,"gsc-result-selector gsc-one-result"),i=U(R.blank,"gsc-result-selector gsc-more-results"),l=U(R.blank,"gsc-result-selector gsc-all-results");ja(g,R["show-one-result"]);ja(i,R["show-more-results"]);ja(l,R["show-all-results"]);T(e,g);T(e,i);T(e,l);na(g,this.e[a].Wi);na(i,this.e[a].Vi);na(l,this.e[a].Ti);this.e[a].Id=e;this.e[a].Nd(google[I].C.Tc);
T(this.e[a].cb,this.e[a].Id);na(this.e[a].Kc,this.e[a].Si);if(this.e[a].h.pa)this.e[a].$=rb("","gsc-configLabel"),o(this.e[a].$,R.blank),Z(this.e[a].$,"gsc-twiddle-closed"),T(d,this.e[a].$),na(this.e[a].$,this.e[a].Ri),ja(this.e[a].$,R.settings),this.e[a].Pa=V("gsc-config"),Z(this.e[a].Pa,this.e[a].h.nb),this.e[a].pb=xb("gsc-config"),Z(this.e[a].pb,this.e[a].h.nb),this.e[a].pb.onsubmit=this.e[a].Qi,T(this.e[a].Pa,this.e[a].pb),oa(this.e[a].Pa[H],"none");this.e[a].X=V("gsc-results");d=this.e[a].h.rc();
Z(this.e[a].X,d);this.e[a].v[N]==f&&T(this.Ua,this.e[a][N]);T(this.e[a][N],c);this.e[a].Pa&&T(this.e[a][N],this.e[a].Pa);T(this.e[a][N],this.e[a].X)};google[I].b[E].Ff=function(a){var c=this.e[a],d={},e=c.h.ci();d.ba=qb(e);d.L=f;d.Ld=c.h;d.z=c.h.z;na(d.ba,S(this,this.tj,[a]));this.k[a]=d;T(this.la,d.ba);a="gs-spacer";ib("opera")&&(a+=" gs-spacer-opera");a=rb(" ",a);T(this.la,a);c.v.og(google[I].b.eb)};
google[I].b[E].Hb=function(a,c){var d=f,e=f;c?c.T?(this.T=c.T,d=c[t],e=c.sg,this.W=c.W):this.T=google[I].b.Ma:this.T=google[I].b.Ma;ra(this,V(this.W?"gsc-control-searchbox-only":"gsc-control"));d!=f?(ga(this,d),this[t].onkeyup=this.hi,this[t].onpaste=this.ii):(e==f&&(e=this[N]),d=new google[I].J(!0,e),d.rg(this,this[va]),d.qg(this,this.ed),ga(this,d[t]),this.Jb&&d.gi());if(!this.W){this.Ua=V("gsc-resultsbox-invisible");if(this.T==google[I].b.Aa){this.la=V("gsc-tabsAreaInvisible");T(this[N],this.la);
this.k=[];for(d=this.t=0;d<this.e[D];d++)this.Ff(d)}this.da=this[N];if(this.Oa)this.da=V("gsc-wrapper"),this.S=V("gsc-adBlockInvisible"),this.Q=V("gsc-adBlockInvisible"),T(this.da,this.S),T(this[N],this.Q),T(this[N],this.da);T(this.da,this.Ua);for(d=0;d<this.e[D];d++)this.Df(d),this.T==google[I].b.Aa&&(Z(this.k[d].ba,"gsc-tabHeader"),Z(this.k[d].L,"gsc-tabData"),d==this.t?(Z(this.k[d].ba,"gsc-tabhActive"),Z(this.k[d].L,"gsc-tabdActive")):(Z(this.k[d].ba,"gsc-tabhInactive"),Z(this.k[d].L,"gsc-tabdInactive")))}a&&
typeof a=="string"&&(a=m[x](a));if(a&&(ob(a,this[N]),(d=this.Uh())&&d<300))this.li=!0,Z(this[N],"gsc-narrow")};Q(google[I].b[E],"draw",google[I].b[E].Hb);google[I].b[E].mj=function(a){switch(a){case google[I].b.ef:case google[I].b.ic:case google[I].b.df:this.Jc=a;break;default:this.Jc=google[I].b.ic}};Q(google[I].b[E],"setTimeoutInterval",google[I].b[E].mj);
google[I].b[E].ej=function(a,c,d){if(d)switch(d){case google[I].b.Ie:case google[I].b.He:case google[I].b.Ge:case google[I].b.Fe:case google[I].b.Ee:this.Ad=R[d];break;default:this.Ad=d}this.uc=mb(a,c)};Q(google[I].b[E],"setOnKeepCallback",google[I].b[E].ej);O=google[I].b[E];O.Bc=function(a){var c=a.z;if(this.Jb){if(c=="web"&&a.F!=google[I].g.aa)return!1;return!0}else return c=="blog"||c=="image"?!0:!1};
O.tj=function(a){if(this.t!=a)if($(this.k[this.t].ba,"gsc-tabhActive"),$(this.k[this.t].L,"gsc-tabdActive"),Z(this.k[this.t].ba,"gsc-tabhInactive"),Z(this.k[this.t].L,"gsc-tabdInactive"),this.t=a,a=this.k[this.t].Ld,Z(this.k[this.t].ba,"gsc-tabhActive"),$(this.k[this.t].ba,"gsc-tabhInactive"),this.Oa&&(this.Bc(a)?this.Ob():this.od()),this.Bd&&a.Uf==this.Bd)Z(this.k[this.t].L,"gsc-tabdActive"),$(this.k[this.t].L,"gsc-tabdInactive");else{var c=m[x](google[I].b.Pc);if(!c)c=m[A]("div"),c.id=google[I].b.Pc,
c[s](m.createTextNode("Loading...")),this.k[this.t].L[ab].insertBefore(c,this.k[this.t].L);this.qd(a,this.k[this.t].L,this.Bd)}};O.Ob=function(){this.Oa&&(r(this.S,"gsc-adBlockInvisible"),r(this.Q,"gsc-adBlockInvisible"),this.ya&&$(this.da,"gsc-thinWrapper"))};O.od=function(){this.Oa&&(r(this.S,this.wb&&this.wb>0?"gsc-adBlock":"gsc-adBlockInvisible"),this.vb&&this.vb>0?(r(this.Q,"gsc-adBlockVertical"),Z(this.da,"gsc-thinWrapper")):(r(this.Q,"gsc-adBlockInvisible"),$(this.da,"gsc-thinWrapper")))};
O.submit=function(){if(this[t][y][D])if(this.W){var a=this.W.gg+(this.W.gg[Ba]("?")>=0?"&":"?")+h(this.W.Li)+"="+h(this[t][y]);this.W.mi?k.open(a):k.location=a}else this[M]();else this.ed();return!1};Q(google[I].b[E],"submit",google[I].b[E][va]);google[I].b[E].pc=function(){this.la&&!this.sj&&(!this.Jb||this.e[D]>1)&&r(this.la,"gsc-tabsArea")};
google[I].b[E].tf=function(a){var c=this;return function(d,e){if(e)a?c.wb=1:c.vb=1,c.wb>0&&(c.ya&&c.vb>1||!c.ya)?(k[ua](c.Lh),c.od()):c.Lh=k[Pa](function(){c.od()},200)}};
pa(google[I].b[E],function(a,c){var d;if(a){d=a;if(this[t].onfocus)this[t].onfocus();p(this[t],d)}else d=this[t][y];if(d[D]){this.Fb=!1;r(this.Ua,"gsc-resultsbox-visible");this.pc();this.Mb=google[K].createGuidArg_();var e=this.Oa;e&&this.di&&this.T==google[I].b.Ma&&(e=!1);var g=this.ki(),i=this.ji();g==b&&!this.Za&&!this.Lb&&(e=!1);if(e){this.Yi();e="w"+this.ua;this.ya&&(e=e+"n"+this.ia);var l;if(this.Lb){this.Ua[H].visibility="hidden";this.Ob();o(this.S,"");o(this.Q,"");this.fa={};this.fa.pubId=
this.Za||"google-coop";this.fa.gcsc=!0;g?this.fa.cx=g:i&&(this.fa.cref=i);this.fa.hl=google[I][L]?h(google[I][L]):f;this.fa.adtest=this.$c?"on":f;this.fa.adsafe=this.Zc||f;this.fa.query=d;if((i=google[I].a.Zh())&&i in google[I].b.Wa){var i=google[I].b.Wa[i],q;for(q in i)this.fa[q]=i[q]}google&&google.ads&&google.ads[I]&&google.ads[I].Ads?this.dg():this.Gd=!0}else l="http://www.google.com/"+(g?"cse":"search")+"?output=js&num=0&ie=utf8&oe=utf8&q="+h(d)+"&hl="+h(google[I][L])+"&ad="+h(e)+"&js=uds&"+
this.Mb;g&&(l+="&cx="+g);this.Za&&(l+="&client="+h(this.Za));this.rf&&(l+="&channel="+h(this.rf));this.$c&&(l+="&adtest=on");this.sf&&(l+="&ip="+h(this.sf));this.Zc&&(l+="&adsafe="+h(this.Zc));this.vf&&(l+="&useragent="+h(this.vf));if(!this.Lb){var u=this;k.google_afs_request_done=function(a){u.oi(a)};lb(l)}}this.Bd=d;if(this.T==google[I].b.Aa)this.qd(this.k[this.t].Ld,this.k[this.t].L,d,c);else for(g=0;g<this.e[D];g++)this.qd(this.e[g].h,this.e[g][N],d,c)}});Q(google[I].b[E],"execute",google[I].b[E][M]);
O=google[I].b[E];
O.dg=function(){this.vb=this.wb=0;if(this.ua&&this.ua>0)this.Bg={container:this.S,number:this.ua,callback:this.tf(!0),lines:2},r(this.S,"gsc-adBlockNoHeight"),qa(this.S[H],"0px");if(this.ya&&this.ia&&this.ia>0)this.pj={container:this.Q,number:this.ia,callback:this.tf(!1)},r(this.Q,"gsc-adBlockVertical"),Z(this.Q,"gsc-adBlockNoHeight"),Z(this.da,"gsc-thinWrapper"),qa(this.Q[H],"0px");this.ua&&this.ua>0&&(this.ya&&this.ia&&this.ia>0?new google.ads[I].Ads(this.fa,this.Bg,this.pj):new google.ads[I].Ads(this.fa,this.Bg))};
O.qd=function(a,c,d,e){!a.Qb&&this.T!=google[I].b.Aa&&($(c,"gsc-resultsbox-invisible"),Z(c,"gsc-resultsbox-visible"));this.Kd&&this.Kd(this,a,d);if(a.Ha)a.Ha=f;a.Mb=this.Mb;e?a.cg(e):a[M](d)};O.ki=function(){for(var a=0;a<this.e[D];a++){var c=this.e[a].h;if(c.z=="web"&&c.F!=google[I].g.aa&&c.F==google[I].g.Gb)return c.l}return f};O.ji=function(){for(var a=0;a<this.e[D];a++){var c=this.e[a].h;if(c.z=="web"&&c.F!=google[I].g.aa&&c.F==google[I].g.Pj)return c.l}return f};
O.oi=function(a){k.google_afs_request_done=f;if(this.S)if(o(this.S,""),o(this.Q,""),this.wb=this.vb=0,!a||a[D]<1)this.Ob();else{if(!this.la)for(var c=0;c<this.e[D];c++){var d=this.e[c].h;if(this.Bc(d)){this.Ob();return}}r(this.S,"gsc-adBlock");var d=!1,e=m[A]("h2"),c="";this.$c&&(c="*DEBUG* ");c+=R["ads-by-google"];o(e,c);T(this.S,e);for(var g=a[D],c=0;c<g;c++){var i=a[c];if(i[Ha]=="text/wide"){this.wb++;var l=V("gsc-ad"),q=Y(i.url,i.line1,google[I].a.Cb);T(l,q);q=m[A]("cite");o(q,i.visible_url);
T(l,q);q=rb();o(q,i.line2);T(l,q);T(this.S,l)}else this.ya&&(this.vb++,d||(d=!0,Z(this.da,"gsc-thinWrapper"),T(this.Q,e[Ga](!0)),r(this.Q,"gsc-adBlockVertical")),l=V("gsc-ad"),q=Y(i.url,i.line1,google[I].a.Cb),T(l,q),q=rb(),o(q,i.line2+"<br/>"+i.line3),T(l,q),q=m[A]("cite"),o(q,i.visible_url),T(l,q),T(this.Q,l))}this.ya&&!d&&$(this.da,"gsc-thinWrapper");if(this.la)d=this.k[this.t].Ld,this.Bc(d)&&this.Ob();this.Zb&&this.kg&&this.Zb(this,"ads")}};
O.ti=function(){var a=this[t][y];if(a&&a!="")this.tb&&k[ua](this.tb),this.tb=k[Pa](S(this,google[I].b[E][M],[f]),this.Jc)};O.ui=function(){this.tb&&k[ua](this.tb);this.tb=k[Pa](S(this,google[I].b[E][M],[f]),this.Jc)};O.Yi=function(){var a,c;switch(this.uf){case google[I].a.fb:a=3;c=5;break;case google[I].a.Ba:a=2;c=4;break;default:a=1,c=2}if(this.ua==b)this.ua=a;if(this.ia==b)this.ia=c};
O.Z=function(a){if(a>0&&a<=8)this.Wb=a;else switch(a){case google[I].a.Ba:case google[I].a.fb:this.Wb=google[I].a.Ba;break;default:case google[I].a.ea:this.Wb=google[I].a.ea}for(var c=0;c<this.e[D];c++)this.e[c].h.Z(a);this.uf=a};Q(google[I].b[E],"setResultSetSize",google[I].b[E].Z);google[I].b[E].ac=function(a){this.ab=a;for(var c=0;c<this.e[D];c++)this.e[c].h.ac(a)};Q(google[I].b[E],"setLinkTarget",google[I].b[E].ac);google[I].b[E].bc=function(a){for(var c=0;c<this.e[D];c++)this.e[c].v.bc(a)};
Q(google[I].b[E],"setNoResultsString",google[I].b[E].bc);O=google[I].b[E];O.Ei=function(a){a.rd?this.bb(a,!1):this.bb(a,!0)};O.bb=function(a,c,d){c?($(a.cb,"gsc-twiddle-closed"),Z(a.cb,"gsc-twiddle-opened"),a.rd=!0,oa(a.X[H],"block")):($(a.cb,"gsc-twiddle-opened"),Z(a.cb,"gsc-twiddle-closed"),a.rd=!1,oa(a.X[H],"none"),o(a.Nb,d?"(0)":"("+a.h.results[D]+")"))};O.ri=function(a){this.cc(a,!1,!0);return!1};O.Di=function(a){a.h.ob&&(a.hd?this.cc(a,!1,!0):this.cc(a,!0,!0))};
O.cc=function(a,c,d){if(c){if(a.$&&a.h.pa)Z(a.$,"gsc-twiddle-opened"),$(a.$,"gsc-twiddle-closed"),o(a.$,R[Va]),a.hd=!0,oa(a.Pa[H],"block"),a.h.pa(a.pb,!0)}else if(a.$&&a.h.pa)$(a.$,"gsc-twiddle-opened"),Z(a.$,"gsc-twiddle-closed"),o(a.$,R.blank),a.hd=!1,a.h.pa(a.pb,!1),oa(a.Pa[H],"none"),d&&this[M]()};O.wi=function(a){this.uc&&this.uc(a)};O.Bh=function(){this.Fb=!0};Q(google[I].b[E],"cancelSearch",google[I].b[E].Bh);
google[I].b[E].ed=function(){p(this[t],"");if(this[t].onblur)this[t].onblur();r(this.Ua,"gsc-resultsbox-invisible");this.la&&r(this.la,"gsc-tabsAreaInvisible");this.S&&r(this.S,"gsc-adBlockInvisible");this.Q&&(r(this.Q,"gsc-adBlockInvisible"),$(this.da,"gsc-thinWrapper"));for(var a=0;a<this.e[D];a++){this.e[a].Qb||($(this.e[a][N],"gsc-resultsbox-visible"),Z(this.e[a][N],"gsc-resultsbox-invisible"));var c=this.e[a];nb(c.X);c.G=f;this.bb(c,!1,!0);this.cc(c,!1,!1)}};
Q(google[I].b[E],"clearAllResults",google[I].b[E].ed);
google[I].b[E].ca=function(a){if(this.Lb&&a==this.e[this.t])this.Ua[H].visibility="visible";this.k&&this.k[this.t]&&this.k[this.t].L&&(Z(this.k[this.t].L,"gsc-tabdActive"),$(this.k[this.t].L,"gsc-tabdInactive"));var c=m[x](google[I].b.Pc);c&&c[ab][Xa](c);var d,e=!1,g;if(!this.Fb){nb(a.X);a.G=f;this.bb(a,!1,!0);this.cc(a,!1,!1);a.Nd(google[I].C.Tc);if(c=a.h.spelling)if(c.html||a.h.Ef(c),c.html){var i=c.html[Ga](!0),l=i[Ja]("a");l&&l[D]>0&&na(l[0],S(this,google[I].b[E][M],[c.correctedQuery]));g=V(a.h.rc());
Z(g,"gsc-result");T(g,i);T(a.X,g)}var l=a.h.context,q=this.la&&l;if(this.Jb&&!this.wh){if(q){g=l[La];for(c=0;c<this.k[D];c++)if(i=this.k[c],i.z==a.h.z){var u=a.h;g&&!a.h.Ab&&ob(i.ba,pb(g));break}this.wh=!0}this.pc()}if((d=a.h.promotions)&&d[D]>0)for(c=0;c<d[D];c++)i=d[c],i.html||a.h.Cf(i),i.html&&(g=V(a.h.rc()),Z(g,"gsc-result"),i=i.html[Ga](!0),T(g,i),T(a.X,g));var z=a.h.results;a.h.Kb&&a.h.completionStatus>=400?(z=[],z[sa](a.h.Rh())):z[D]==0&&a.v.Tb&&a.h.completionStatus==200&&(z=[],z[sa](a.h.Sh(a.v.Tb)));
for(c=0;c<z[D];c++)if(d=z[c],d.html||a.h.K(d),d.html){e=!0;g=V(a.h.rc());Z(g,"gsc-result");a.h.gc&&Z(g,"gsc-result-"+a.h.gc);i=d.html[Ga](!0);if(d.GsearchResultClass==google[I].c.I){if(a.v.U&&(a.v.U[v]!=a.h.U[v]||a.v.U[bb]!=a.h.U[bb]))for(var G=i[Ja]("img"),W=0;W<G[D];W++)google[I].a.xb(d.tbWidth,d.tbHeight,a.v.U,G[W],!0)}else if(d.GsearchResultClass==google[I].s.I&&a.v.Mc){G=i[Ja]("img");for(W=0;W<G[D];W++)google[I].a.xb(d.tbWidth,d.tbHeight,a.v.Mc,G[W])}T(g,i);if(this.uc)i=this.Ad,G=U("","gsc-keeper"),
o(G,i),T(g,G),na(G,S(this,google[I].b[E].wi,[d,a]));if(c>=a.h.Yf){if(!a.G)a.G=V("gsc-expansionArea"),T(a.X,a.G),a.v.ga==google[I].b.Xa&&oa(a.G[H],"none");T(a.G,g)}else T(a.X,g)}if(!a.G&&a.h[F])a.G=V("gsc-expansionArea"),T(a.X,a.G);a.G&&a.h.w&&a.h.gwsUrl&&a.h[F]&&(c=V("gsc-cursor-box"),g=this.Hh(a),c[s](g),T(a.G,c));e?(o(a.Nb,"("+a.h.results[D]+")"),a.v.ga==google[I].b.Xa||a.v.ga==google[I].b.eb?this.bb(a,!0):this.bb(a,!1),(c=a.h.If())&&T(a.X,c)):(o(a.Nb,"(0)"),o(a.X,""),this.bb(a,!1));a.v.ga=a.v.$f;
this.Zb&&this.Zb(this,a.h);if(this.Jb&&q&&!this.qf&&l.facets){a=this[t][y];e=l.facets;for(c=0;c<e[D];c++){l=e[c];q=new google[I].g;if(u){u.l&&q.Ka(u.l,l.label);if(u.H)q.H=u.H;if(u.wa)q.wa=u.wa}q.dc(l.anchor);this.jb(q);q.Z(u.Ia);this.T!=google[I].b.Aa&&q[M](a)}this.e[D]>1&&!this.qf&&r(this.la,"gsc-tabsArea");for(c=0;c<this.e[D];c++)this.k[c]||(this.Ff(c),this.Df(c),Z(this.k[c].ba,"gsc-tabHeader"),Z(this.k[c].L,"gsc-tabData"),Z(this.k[c].ba,"gsc-tabhInactive"),Z(this.k[c].L,"gsc-tabdInactive"));this.qf=
!0}}};Q(google[I].b[E],"onSearchComplete",google[I].b[E].ca);google[I].b[E].Hh=function(a){for(var c=V("gsc-cursor"),d=a.h[F],e=0;e<d.pages[D];e++){var g="gsc-cursor-page";e==d.currentPageIndex&&(g+=" gsc-cursor-current-page");g=U(d.pages[e].label,g);na(g,S(this,google[I].b[E].Pi,[a,e]));c[s](g)}return c};
google[I].b.Ze={border:"border",borderColor:"border-color",borderStyle:"border-style",borderWidth:"border-width",borderTop:"border-top",borderTopColor:"border-top-color",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomStyle:"border-bottom-style",borderBottomWidth:"border-bottom-width",
borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",color:"color",cssFloat:"float",styleFloat:"float",clear:"clear",cursor:"cursor",display:"display",font:"font",fontFamily:"font-family",fontSize:"font-size",fontStyle:"font-style",fontWeight:"font-weight",height:"height",margin:"margin",marginTop:"margin-top",marginRight:"margin-right",marginBottom:"margin-bottom",marginLeft:"margin-left",overflow:"overflow",padding:"padding",
paddingTop:"padding-top",paddingRight:"padding-right",paddingBottom:"padding-bottom",paddingLeft:"padding-left",textAlign:"text-align",textDecoration:"text-decoration",textTransform:"text-transform",verticalAlign:"vertical-align",visibility:"visibility",width:"width"};
google[I].b.Qf=function(a,c){if(ib("safari")||ib("konqueror"))alert("google.search.SearchControl.inlineCurrentStyle is not supported on Safari");else{var d=!0;c&&(d=c);if(d)for(d=0;d<a.childNodes[D];d++)google[I].b.Qf(a.childNodes[d],!0);if(a.nodeType==1){var e,g,i=!1,d=!1;k[Ua]?(e=k[Ua](a,f),i=g=!0):a[Ya]&&(e=a[Ya],g=!1,i=!0);if(i){for(var l in e)if(google[I].b.Ze[l]){var i=google[I].b.Ze[l],q=e[l];l=="display"&&q=="none"&&(o(a,""),d=!0);e[l]!=""&&(g?a[H].setProperty(i,q):a[H][Fa](i,q))}if(d&&!g)a.outerHTML=
'<div style="display:none"/>'}}}};Q(google[I].b,"inlineCurrentStyle",google[I].b.Qf);google[I].b[E].Uh=function(a){var a=a?a:this[N],c=f;k[Ua]?c=k[Ua](a,f):a[Ya]?c=a[Ya]:m.defaultView[Ua]&&(c=m.defaultView[Ua](a,f));return c?ca(c[v],10):300};google[I].b[E].yb=function(a,c){this.Zb=mb(a,c)};Q(google[I].b[E],"setSearchCompleteCallback",google[I].b[E].yb);google[I].b[E].kj=function(a,c){this.Kd=mb(a,c)};Q(google[I].b[E],"setSearchStartingCallback",google[I].b[E].kj);
google[I].b[E].Fd=function(a,c){a.Nd(c);var d=!1;switch(c){default:case google[I].C.Vc:a.G&&oa(a.G[H],"none");break;case google[I].C.Uc:a.G&&oa(a.G[H],"block");a.h.Ia!=google[I].a.ea&&(d=!0);a.h.Z(google[I].a.ea);break;case google[I].C.$e:a.G&&oa(a.G[H],"block"),a.h.Ia!=google[I].a.Ba&&(d=!0),a.h.Z(google[I].a.Ba)}if(d&&(d=this[t][y],d[D]))this.Fb=!1,r(this.Ua,"gsc-resultsbox-visible"),this.pc(),a.Qb||($(a[N],"gsc-resultsbox-invisible"),Z(a[N],"gsc-resultsbox-visible")),a.v.ga=google[I].b.eb,a.h[M](d)};
google[I].b[E].Pi=function(a,c){this.Fb=!1;r(this.Ua,"gsc-resultsbox-visible");this.pc();a.Qb||($(a[N],"gsc-resultsbox-invisible"),Z(a[N],"gsc-resultsbox-visible"));a.v.ga=google[I].b.eb;a.h.Nf(c)};
google[I].J=function(a,c,d){var e=xb("gsc-search-box");e.acceptCharset="utf-8";var g=f,i=R["search-uc"],l=R[I];if(d){if(d.buttonText)l=i=d.buttonText;if(d.clickableBrandingUrl)g="http://www.google.com",typeof d.clickableBrandingUrl=="string"&&d.clickableBrandingUrl[Ca](/^http:\/\/[a-z]*\.google\.com/)&&(g=d.clickableBrandingUrl),g=wb(g,f,"_BLANK"),r(g,"gsc-branding-clickable")}this.Ac=yb(i,"gsc-search-button");ja(this.Ac,l);a?(d="gsc-branding-img",this.fd=U(R.blank,"gsc-clear-button"),ja(this.fd,
R["clear-results"])):d="gsc-branding-img-noclear";ga(this,zb(f,"gsc-input",f));this[t].name="search";ja(this[t],l);l=sb(f,f,"gsc-search-box");T(e,l);l=tb(l,0);this.Rf=X(l,"gsc-input");i=X(l,"gsc-search-button");a&&(a=X(l,"gsc-clear-button"),T(a,this.fd));T(this.Rf,this[t]);T(i,this.Ac);a=sb(f,f,"gsc-branding");T(e,a);l=tb(a,0);this.userDefinedCell=X(l,"gsc-branding-user-defined");var a=X(l,"gsc-branding-text"),l=X(l,d),i=U(R["powered-by"],"gsc-branding-text"),q=google[K][Ia]+"/css/small-logo.png";
ib("msie")?(d=V(d),d[H].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+q+'")',ha(d[H],"51px"),qa(d[H],"15px")):d=vb(q,f,f,d);T(a,i);g?(T(g,d),T(l,g)):T(l,d);this.ig=e;nb(c);T(c,this.ig)};P("google.search.SearchForm",google[I].J);google[I].J.Jf=function(){return"#FFFFFF url(//www.google.com/cse/intl/"+google[I][L]+"/images/google_custom_search_watermark.gif) left no-repeat"};
google[I].J[E].rg=function(a,c){this.wg=S(this,this.rj,[this]);this.Hc=S(a,c,[this]);this.ig.onsubmit=this.wg;na(this.Ac,this.wg)};Q(google[I].J[E],"setOnSubmitCallback",google[I].J[E].rg);google[I].J[E].qg=function(a,c){na(this.fd,S(a,c,[this]))};Q(google[I].J[E],"setOnClearCallback",google[I].J[E].qg);google[I].J[E].rj=function(){var a=this.Rf[za],c=this[t][y];this.Hc&&this.Hc();if(ib("msie")){var d=this,e,e=c[D]*8>=a?a-6:"99%";k[Pa](function(){ha(d[t][H],e)},1)}return!1};
pa(google[I].J[E],function(a){a&&p(this[t],a);this.Hc&&this.Hc()});Q(google[I].J[E],"execute",google[I].J[E][M]);google[I].J[E].gi=function(){var a=this[t],c=function(){if(a[y]=="")a[H].background=google[I].J.Jf()};a.onblur=c;a.onfocus=function(){a[H].background="#FFFFFF"};c()};google[I].qe=function(a,c,d,e){this.qa=d[Ga](!0);this.qa.id="gsci-content"+e;d[ab].insertBefore(this.qa,d);d=new google[I].A;d.pg(c);this.nc=new google[I].i(a);this.nc.Z(google[I].a.ea);this.nc.Hb(this.qa,d);this.sc=!1;this.zc=f;la(this,f);this.Ra=f};O=google[I].qe[E];O.vd=function(){oa(this.qa[H],"none");$(this.qa,"fade")};O.show=function(){oa(this.qa[H],"block");$(this.qa,"fade")};O.Qh=function(){Z(this.qa,"fade")};
O.send=function(a,c){if(!this.sc){var d=this;this.nc.yb(this,function(){this.sc=!1;if(d.zc)d.zc(d),d.zc=f});this.sc=!0;this.nc[M](a,c)}};O.Md=function(a){this.zc=a};google[I].Bb=function(a,c,d,e){this.Cd=this.rb=f;for(var g=0;g<e;g++)this.Sf(new google[I].qe(a,c,d,g));this.wc={};this.xa=f};google[I].Bb[E].Sf=function(a){la(a,this.rb);a.Ra=f;this.rb==f?this.Cd=a:this.rb.Ra=a;this.rb=a};
google[I].Bb[E].Mi=function(a){a.Ra==f?this.rb=a[Qa]:la(a.Ra,a[Qa]);a[Qa]==f?this.Cd=a.Ra:a[Qa].Ra=a.Ra;a.Ra=f;la(a,f);return a};google[I].Bb[E].get=function(a,c,d){if(!a&&d)d(f);else{if(d)for(var e=this.rb;e!=f;e=e[Qa])e.Md(f);if(a in this.wc)e=this.wc[a],d&&(e.sc?e.Md(d):d(e));else{e=this.Cd;delete this.wc[e.xk];if(this.xa==e)e.vd(),this.xa=f;this.wc[a]=e;d&&e.Md(d);e.send(a,c)}this.Mi(e);this.Sf(e)}};
google[I].Bb[E].show=function(a,c){if(a){this.xa!=f&&this.xa.Qh();var d=this;this.get(a,c,function(a){d.xa&&d.xa.vd();a&&a[ta]();d.xa=a})}else this.xa&&this.xa.vd(),this.xa=f};
google[I].B=function(a,c){this.nd=a;c&&typeof c=="string"&&(c=m[x](c));c&&o(c,google[I].B.Rg);this.P=m[x]("gsci-query");this.ei=m[x]("gsci-hidden");this.qa=m[x]("gsci-content");this.Gi=m[x]("gsci-padding");this.fi=m[x]("gsci-hide");this.tg=m[x]("gsci-show");this.Ch=m[x]("gsci-clear");var d=m[x]("gsci-sform");d&&p(d.cx,this.nd);this.na=f;this.Qd=!1;this.Pf()};P("google.search.CustomInstantSearchControl",google[I].B);google[I].B.lh=300;google[I].B.hh=20;google[I].B.Wg=5;
google[I].B.Rg=['<form id="gsci-sform" name="f" onsubmit="return q.value != \'\'">\n  <div class="gsci-sbox">\n    <div class="gsci-sinput">\n      <input class="gsci-entry" id="gsci-query" name="q" type="text"\n        value="" autocorrect="off" autocomplete="off" maxlength="1024"\n        onfocus="this.value = this.value">\n      <div class="gsci-entry" id="gsci-grey" name="g"\n        onfocus="this.parentNode.childNodes[0].focus()">\n        <span id="gsci-hide"></span><span id="gsci-show"></span>\n      </div>\n      <a class="gsci-cross" id="gsci-clear" title="Clear search">\u00d7</a>\n    </div>\n  </div>\n  <input type="hidden" name="cx" value="">\n  <input class="gsci-sbutton" id="gsci-search" type="submit"\n    value="Search" title="Search">\n</form>\n<input id="gsci-hidden" type="text" style="display: none;">\n<div id="gsci-padding"></div>\n<div class="gsci-results" id="gsci-content" style="display: none;"></div>','<link href="'+
google[K][Ia]+'/css/gcustominstantsearch.css" type="text/css" rel="stylesheet">','<\!--[if gte IE 6]>\n  <style type="text/css"> #gsci-grey { padding-left: 0px; } </style>\n<![endif]--\>\n<\!--[if lte IE 7]>\n  <style type="text/css"> #gsci-query { top: -1px; } </style>\n<![endif]--\>'][cb]("\n");google[I].B.Pd=function(a,c){m.all?a.innerText=c:a.textContent=c};
google[I].B.bi=function(){if(m.getElementsByClassName)return m.getElementsByClassName("gsc-completion-container")[0];else for(var a=m[Ja]("table"),c=0;c<a[D];c++){var d=a[c];if(d[Ma]=="gsc-completion-container")return d}return f};O=google[I].B[E];O.Da=function(a,c,d){a.addEventListener?a.addEventListener(c,this.bd(d),!1):a.attachEvent&&a.attachEvent("on"+c,this.bd(d))};O.bd=function(a){var c=this;return function(){return a[$a](c,arguments)}};
O.Pf=function(){this.Vd=f;this.ta="";this.Rd=f;this.Sd=0;this.ec=-1;this.Ec(!0)};O.La=function(a){var c=this.P[y],d=c[D],e=a[Ba](c);google[I].B.Pd(this.fi,c);a&&e==0?google[I].B.Pd(this.tg,a.substring(d)):google[I].B.Pd(this.tg,"")};O.jc=function(a){var c=0;if(a)c=a;else if(a=google[I].B.bi())this.Da(a,"mouseover",this.Bi),this.Da(a,"mouseout",this.Ai),c=a.clientHeight+7;this.Gi[H].marginTop=c+"px"};
O.xg=function(a,c){if(a&&a[D]>1&&a[1][D]>0){this.jc();var d=a[1][0][0];this.na[ta](d,c);this.La(d);this.Rd=a[1];this.Sd=a[1][D];this.ec=-1;this.ta=d}else{this.jc(0);k[ua](this.Vd);var e=this;this.Vd=k[Pa](function(){e.Vd=f;e.na[ta](e.P[y]);e.La("")},200);this.Rd=f;this.Sd=0;this.ec=-1;this.ta=""}};O.Ec=function(a){this.P[H].background=a?google[I].J.Jf():"transparent"};O.vi=function(){this.La(this.ta)};O.Ci=function(){this.La(this.ta)};
O.xi=function(a){if((a[Ea]==google[I].d.Ya||a[Ea]==google[I].d.za||a[Ea]==google[I].d.Nc)&&!this.Qd){this.Qd=!0;var c=this.Rd,d=this.ec,e=this.Sd;switch(a[Ea]){case google[I].d.Ya:d=(d+e+1)%(e+1)-1;break;case google[I].d.za:d=(d+2)%(e+1)-1}this.ec=d;d>=0&&c&&c[D]>d?this.na.get(c[d][0]):this.ta?this.na.get(this.ta):this.na.get(this.P[y])}};
O.zi=function(a){a[Ea]==google[I].d.Ya||a[Ea]==google[I].d.za||a[Ea]==google[I].d.Nc?(this.Qd=!1,this.ec==-1?(this.ta?this.na[ta](this.ta):this.na[ta](this.P[y]),this.La(this.ta)):(this.na[ta](this.P[y]),this.La(""))):a[Ea]==google[I].d.re&&this.jc(0)};O.qi=function(){this.P[y]==""&&this.Ec(!0);var a=this;k[Pa](function(){a.jc(0)},google[I].B.lh)};O.si=function(){this.Ec(!1)};O.Fi=function(){p(this.P,"");this.na[ta]("");this.La("");this.Pf()};O.Bi=function(){this.La("")};O.Ai=function(){this.La(this.ta)};
O.aj=function(){this.Da(this.P,"input",this.vi);this.Da(this.P,"propertychange",this.Ci);this.Da(this.P,"keydown",this.xi);this.Da(this.P,"keyup",this.zi);this.Da(this.P,"blur",this.qi);this.Da(this.P,"focus",this.si);this.Da(this.Ch,"click",this.Fi)};pa(O,function(a){this.na=new google[I].Bb(this.nd,this.ei,this.qa,google[I].B.hh);google[I].i.ad(this.nd,this.P,"gsci-sform",f,this.bd(this.xg),google[I].B.Wg);this.aj();a&&(p(this.P,a),this.Ec(!1),this.xg(f))});Q(google[I].B[E],"execute",google[I].B[E][M]);google[I].i=function(a,c){google[I].b[J](this);this.Jb=!0;this.Z(google[I].a.Ba);var d={iframes:!0};d.adtest=c&&c.adtest||f;this.Ib("",d);this.ag=!1;this.qb=new google[I].g;this.Af=typeof a=="string"?a:f;if(a==b)a={crefUrl:"http://www.google.com/coop/tools/autocse?referer="+k[Ta]},this.yj=!0;this.qb.Ka(a);this.qb.Ic=R.cse;c&&(c[google[I].a.ib]&&this.qb.Y(google[I].a.ib,c[google[I].a.ib]),c[google[I].a.hb]&&this.qb.Y(google[I].a.hb,c[google[I].a.hb]));this.jb(this.qb);this.bc(google[I].b.Ke);this.vj=
(new Date)[C]()};P("google.search.CustomSearchControl",google[I].i);gb(google[I].i,google[I].b);
google[I].d=function(a,c,d,e,g){this.$b=a;this.Jh=d;this.Sa=c[y];this.Wf="";this.zg=this.yg=0;this.Vb=!1;this.Ji="";this.Ub={};this.Ed=g;this.Ii=!1;a=n[xa](n.random()*2E4)+google[I].d.Bf;this.kc=google[I].d.Hg+a;this.bg=google[I].d.jh+a;google[I].d.Bf++;var i=this;this.hg=f;this.Zf=!!e;google[I].i[this.kc]=function(a){i.Ni(a);e&&e(a,i.hg)};google[I].i[this.bg]=function(a,c){i.hg=c};this.va=c.id;if(!this.va)this.va="q"+this.kc,c.id=this.va;this.mc="c"+this.kc;this.fc=!1;this.xj=function(){try{if(k[Aa]&&
k.JSON){var a=(new Date)[Ka](),c=a+"x";k[Aa].setItem(c,a);this.fc=k[Aa].getItem(c)===a;k[Aa].removeItem(c);this.jg();k.setInterval(this.jg,google[I].d.qh*1E3)}}catch(d){}};this.Oi=function(a){for(var c=k[Aa],d=google[I].d.Xc,e=[],g=0;g<c[D];g++){var i=c.key(g);i.slice(0,d[D])==d&&e[sa](i)}for(g=0;g<e[D];g++)c.removeItem(e[g]);a.Od(google[I].d.Wc,(new Date)[C]()/1E3)};this.jg=function(){var a=google[I].d,c=i.Kf(a.Wc);c?(new Date)[C]()/1E3-c>=a.rh&&i.Oi(i):i.Od(a.Wc,(new Date)[C]()/1E3)};this.hj=function(a,
c){this.fc&&k[Aa].setItem(a,c)};this.Od=function(a,c){try{this.fc&&this.hj(a,k.JSON.stringify(c))}catch(d){}};this.ai=function(a){if(this.fc)try{var c=k[Aa].getItem(a);if(typeof c=="undefined"||c===f)return c;if(typeof c[y]=="string")return c[y];return c}catch(d){}};this.Kf=function(a){if(this.fc)try{var c=this.ai(a);if(typeof c=="undefined"||c===f)return c;return k.JSON.parse(c)}catch(d){}};this.Lf=function(a){return this.Kf(google[I].d.Xc+a)};this.ij=function(a,c){this.Od(google[I].d.Xc+a,c)}};
google[I].d.Hg="GcrcGcsc";google[I].d.jh="GcrrGcsc";google[I].d.Bf=0;google[I].d.Ce=0;google[I].d.lc=google[I].d.Ce;google[I].d.De=2;google[I].d.Zg=10;google[I].d.Fg=10;google[I].d.Gg=1;google[I].d.gd=google[I].d.De;google[I].d.mh=5E3;google[I].d.cf=500;google[I].d.kh=300;google[I].d.pe=25;google[I].d.mb=google[I].d.pe;google[I].d.Yg=300;google[I].d.Ne=25;google[I].d.Kg=2E3;google[I].d.za=40;google[I].d.Ya=38;google[I].d.Nc=13;google[I].d.re=27;google[I].d.ph=32;google[I].d.Eg=8;google[I].d.ih=45;
google[I].d.$g=5;google[I].d.Xg=5;google[I].d.Fc=!1;google[I].d.Rb="";google[I].d.tc=[];google[I].d.Xc="sayt-";google[I].d.Wc="$sayt-last-clear";google[I].d.rh=900;google[I].d.qh=300;google[I].d.gb=1;google[I].d.Oc=2;
google[I].d.yi=function(a,c){var d=0;if(k&&k[eb]&&k[eb][Ea])d=k[eb][Ea];else if(c&&c.which)d=c.which;if(!a.Vb&&d!=google[I].d.za)return!0;var e=m[x](a.va);if(d==google[I].d.Nc)return a.vg(google[I].d.gb),!1;else if(d==google[I].d.Ya)return a.Xf(d),!1;else if(d==google[I].d.za)return a.Xf(d),!1;else if(d==google[I].d.re){var g=(new Date)[C]();a.xc();p(e,a.Sa);if(g<a.yg+google[I].d.Kg)a.Vb=!1;a.yg=g}if(a.Sa==e[y]||d<=google[I].d.ih&&d!=google[I].d.ph&&d!=google[I].d.Eg)return!0;a.Hd()};
google[I].d.pi=function(a){k[Pa](function(){a.xc()},google[I].d.kh)};google[I].d.Xb=function(a,c,d){if(google[I].d.Rb==d)google[I].d.tc=a;c.ij(d,a);if(c=m[x](c.mc))for(d=0;d<google[I].d.$g;++d){var e=m[x]("google-sayt-result"+d[Ka]());if(d<a[D])if(e)o(e[B],a[d]);else{e=m[A]("tr");e.id="google-sayt-result"+d[Ka]();var g=m[A]("td");o(g,a[d]);e[s](g);c[B][s](e)}else e&&o(e[B],"")}};O=google[I].d[E];
O.$i=function(){var a=m[x](this.va);if(a)a.onkeyup=this.xf(google[I].d.yi,a.onkeyup),a.onblur=this.xf(google[I].d.pi,a.onblur)};O.vg=function(a){var c=m[x](this.va);if(c)if(this.Ja&&a===google[I].d.Oc&&p(c,this.Wf),this.Sa=c[y],this.xc(),typeof this.$b=="string")if(a=m[x](this.$b),this.Ii&&a.onsubmit)a.onsubmit();else a[va]();else this.$b[M]?this.$b[M]():this.$b[va]()};
O.Gc=function(a,c){for(;c&&c.id[Ba]("google-sayt-result")==0;)if(a==google[I].d.Ya)c=c.previousSibling;else if(a==google[I].d.za)c=c.nextSibling;return c};
O.Xf=function(a){var c=m[x](google[I].i.Sc);if(c){google[I].d.Wd(c,this);var d=f;if(a==google[I].d.Ya)d=c[ab].previousSibling,d=google[I].d[E].Gc(a,d);else if(a==google[I].d.za)d=c[ab].nextSibling,d=google[I].d[E].Gc(a,d);d&&google[I].d.Dc(d[B],this,google[I].d.gb)}else if((c=m[x](this.mc))&&a==google[I].d.Ya)c=c[B].lastChild,c=google[I].d[E].Gc(a,c),google[I].d.Dc(c[B],this,google[I].d.gb);else if(c&&a==google[I].d.za)c=c[B][B],c=google[I].d[E].Gc(a,c),google[I].d.Dc(c[B],this,google[I].d.gb);else if(a==
google[I].d.za)this.Vb=!0,this.Hd()};O.xc=function(){var a=m[x](this.mc);a&&a[ab][Xa](a)};
O.Hd=function(){var a=this,c=m[x](a.va);a.Sa=c[y];a.Vb&&(a.zg+google[I].d.mb>(new Date)[C]()?k[Pa](function(){a.Hd()},google[I].d.mb):k[Pa](function(){var d=m[A]("script"),e=(new Date)[C]();d.src=[a.Zf?google[K][Ia]+"/GcompleteSearch?q=":"//clients1.google.com/complete/search?q=",h(c[y]),"&hl=",h(google[I][L]),"&client=partner&source=gcsc&partnerid=",h(a.Jh),"&callback=",h("google.search.CustomSearchControl."+a.kc),a.Zf?"&rcallback="+h("google.search.CustomSearchControl."+a.bg):"","&ds=cse"][cb]("");
a.Ji=c[y];m[Wa][s](d);a.Ub[c[y]]=e;a.zg=e;k[Pa](function(){a.Ag(c[y])},google[I].d.cf)},google[I].d.lc+n[xa](n.random()*google[I].d.gd)))};
O.Ni=function(a){var c=this,d=a[0];delete c.Ub[d];google[I].d.lc=google[I].d.Ce;google[I].d.gd=google[I].d.De;google[I].d.mb>google[I].d.pe&&(google[I].d.mb-=google[I].d.Ne);google[I].d.Fc=!0;var e=m[x](c.va);if(d==e[y]){c.xc();var g=a[1][D];if(!(g<1)){if(c.Ed&&g>c.Ed)g=c.Ed;for(var i=m[A]("tbody"),l=f,q=f,d="",u=0;u<g;++u){q=m[A]("tr");l=m[A]("td");o(l,a[1][u][0]);var z=l.innerHTML.slice(0,a[0][D]),G=l.innerHTML.slice(a[0][D]);o(l,z+"<strong>"+G+"</strong>");c.Ja&&u==0&&(d=z+G);l.onmouseover=c.pd(l,
google[I].d.lg);if(!c.Ja)l.onmouseout=c.pd(l,google[I].d.Wd);l.onmousemove=c.pd(l,google[I].d.Ui);na(l,function(){c.vg(google[I].d.Oc)});q[s](l);i[s](q)}a=m[A]("table");a.id=c.mc;a[s](i);r(a,google[I].i.Ig);a[H].top=google[I].d.Wh(e)+Lb(e,!0)+"px";a[H].left=google[I].d.Vh(e)+"px";m[Wa][s](a);ha(a[H],e[za]+"px");if(d!="")if(google[I].d.Rb==d)google[I].d.Xb(google[I].d.tc,c,d);else if(c.Ja)google[I].d.Rb=d,google[I].d.tc=[],(e=this.Lf(d))?google[I].d.Xb(e,c,d):c.Ja(d,google[I].d.Xb,c)}}};
O.pd=function(a,c){var d=this;return function(){c(a,d)}};O.xf=function(a,c){var d=this;return function(e){a(d,e);c&&c(e)}};
google[I].d.Dc=function(a,c,d){var e=m[x](google[I].i.Sc),g=m[x](c.va);if(c.Ja){if(e)r(e,""),e.id=""}else e&&google[I].d.Wd(e,c);e=a.textContent;if(e==b)e=a.innerText;r(a,google[I].i.nh);a.id=google[I].i.Sc;c.Ja?d===google[I].d.gb?(c.Sa=g[y],p(g,e)):c.Wf=e:(c.Sa=g[y],p(g,e));if(d===google[I].d.gb&&c.Ja&&google[I].d.Rb!=e)google[I].d.Rb=e,google[I].d.tc=[],(a=c.Lf(e))?google[I].d.Xb(a,c,e):c.Ja(e,google[I].d.Xb,c)};google[I].d.lg=function(a,c){google[I].d.Fc||google[I].d.Dc[J](this,a,c,google[I].d.Oc)};
google[I].d.Ui=function(a,c){if(google[I].d.Fc)google[I].d.Fc=!1,a.onmousemove=f,google[I].d.lg[J](this,a,c)};google[I].d.Wd=function(a,c){var d=m[x](c.va);r(a,"");a.id="";p(d,c.Sa?c.Sa:"")};google[I].d.Wh=function(a){var c=0;if(a[Sa]){for(;a[Sa];)c+=a.offsetTop-a.scrollTop,a=a[Sa];c+=a.offsetTop}else a.y&&(c+=a.y);return c};google[I].d.Vh=function(a){var c=0;if(a[Sa]){for(;a[Sa];)c+=a.offsetLeft-a.scrollLeft,a=a[Sa];c+=a.offsetLeft}else a.x&&(c+=a.x);return c};
google[I].d[E].Ag=function(a){var c=this;if(c.Ub[a])if((new Date)[C]()-c.Ub[a]>google[I].d.mh)google[I].d.lc+=google[I].d.Gg,google[I].d.lc*=google[I].d.Fg,google[I].d.gd+=google[I].d.Zg,google[I].d.mb<google[I].d.Yg&&(google[I].d.mb+=google[I].d.Ne),delete c.Ub[a];else k[Pa](function(){c.Ag(a)},google[I].d.cf)};google[I].i.ad=function(a,c,d,e,g,i){if(e)i=google[I].d.Xg;a=new google[I].d(d,c,a,g,i);a.Vb=!0;a.Ja=e;a.$i();e&&a.xj();return a};Q(google[I].i,"attachAutoCompletion",google[I].i.ad);
google[I].i[E].Gf=function(){this.Af?(google[I].i.ad(this.Af,this[t],this),this.ag=!0):this.ag=!1};Q(google[I].i[E],"enableAutoCompletion",google[I].i[E].Gf);google[I].i[E].Hb=function(a,c){var d=c;d||(d=new google[I].A);d.ng(google[I].b.Aa);if(this.yj&&this.e[D]==1)this.sj=!0;google[I].b[E].Hb[J](this,a,d);var e=this.W?"gsc-control-searchbox-only":"gsc-control-cse";r(this[N],e);Z(this[N],e+"-"+google[I][L]);d.wf&&this.Gf()};Q(google[I].i[E],"draw",google[I].i[E].Hb);
pa(google[I].i[E],function(a,c){var d=this[N][za];$(this.da,"gsc-thinWrapper");if(d<google[I].i.ah)this.Oa=!1;else if(d<google[I].i.dh)this.Ib(this.Za,{useNarrowTopAd:!0,includeVerticalAds:!1});else{d={useNarrowTopAd:!1,includeVerticalAds:d>google[I].i.bh};if(this.Vf)d.numTopAds=google[I].i.eh;this.Ib(this.Za,d)}if((new Date)[C]()-this.vj<google[I].i.Cg&&this.Oa)try{var e=fa(k[Ta].href)[w](/\+/g," "),g=fa(a)[w](/\+/g," ");this.Oa=e[Ba](g)!=-1}catch(i){}google[I].b[E][M][J](this,a,c)});
Q(google[I].i[E],"execute",google[I].i[E][M]);google[I].i[E].dc=function(a){this.qb.dc(a)};Q(google[I].i[E],"setUserDefinedLabel",google[I].i[E].dc);google[I].i[E].jb=function(a,c){google[I].b[E].jb[J](this,a,c);a.Cc="gcsc"};Q(google[I].i[E],"addSearcher",google[I].i[E].jb);google[I].i[E].Kh=function(){google[I].b[E].Ib("",{numTopAds:0,numSideAds:0});this.Za=f;this.kg=!1};Q(google[I].i[E],"disableAds",google[I].i[E].Kh);google[I].i[E].cj=function(){this.Vf=!0};Q(google[I].i[E],"setMoreAds",google[I].i[E].cj);
google[I].i.Dg="";Q(google[I].i,"AUTO_PUBID",google[I].i.Dg);google[I].i.ah=250;google[I].i.dh=500;google[I].i.bh=800;google[I].i.Cg=500;google[I].i[E].Vf=!1;google[I].i.eh=4;google[I].i.Sc="csc-completion-selected";google[I].i.nh="gsc-completion-selected";google[I].i.Ig="gsc-completion-container";google[I].s=function(){google[I].a[J](this);this.z="video";this.Va="/GvideoSearch";this.Fa="http://video.google.com/videosearch";this.V=!1;this.ob=!0;this.pa=mb(this,this.Ga);this.nb="gsc-videoConfig";this.p=f};P("google.search.VideoSearch",google[I].s);gb(google[I].s,google[I].a);google[I].s.I="GvideoSearch";Q(google[I].s,"RESULT_CLASS",google[I].s.I);google[I].s.o=[];google[I].s.M=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[I].s.o[i];google[I].s.o[i]=f;a.ca(c,d,e,g)};
Q(google[I].s,"RawCompletion",google[I].s.M);google[I].s[E].ra=function(a,c,d,e){d=d==f?google[I].a.ma(google[I].s.o,this):d;c=this.Ta(c==f?"google.search.VideoSearch.RawCompletion":c,d,e);this.O&&(a=a+" "+this.O);a="&q="+h(a);this.V&&(a+="&scoring=d");c+=a;this.w=a;if(e&&e!=0)this.w=this.w+"&start="+e;return c};
google[I].s[E].K=function(a){a.html&&delete a.html;var c=V(this.Ea());Z(c,"gs-result");var d=V("gs-image-box"),e=V("gs-text-box"),g=sb(),i=tb(g,0),l=X(i,"gs-image-box"),i=X(i,"gs-text-box");T(l,d);T(i,e);T(c,g);g=google[I].a.xb(a.tbWidth,a.tbHeight,this.U);g=vb(a.tbUrl,g[v],g[bb],"gs-image");l=wb(a.url,f,this.u(),"gs-image");r(l,"gs-image");T(l,g);T(d,l);d=Y(a.url,a[La],this.u(),"gs-title");T(e,d);d=U(a[ya],"gs-snippet");ib("msie")&&qa(d[H],"2.6em");T(e,d);d=U(this.sb(new Date(a.published)),"gs-publishedDate");
T(e,d);d=Y("http://"+a.publisher,a.publisher,this.u(),"gs-publisher");T(e,d);a.html=c;this.Na(a.html)};Q(google[I].s[E],"createResultHtml",google[I].s[E].K);
google[I].s.Ih=function(a,c){var d=f;if(a.playUrl&&a.playUrl!=""){var d=a.playUrl,e="gsc-video-player";c&&(e=c);if(ib("opera")){var g=m[A]("object");r(g,e);g[Fa]("type","application/x-shockwave-flash");g[Fa]("data",d)}else g=m[A]("embed"),r(g,e),g[Fa]("type","application/x-shockwave-flash"),g[Fa]("src",d),a.videoType?a.videoType=="Google"?g[Fa]("bgcolor","#000000"):g[Fa]("wmode","transparent"):g[Fa]("bgcolor","#000000");d=V(c);d[s](g)}return d};Q(google[I].s,"createPlayer",google[I].s.Ih);
google[I].s[E].R=function(a){this.V=a==google[I].a.Ca?!0:!1};Q(google[I].s[E],"setResultOrder",google[I].s[E].R);google[I].s[E].Ga=function(a,c){if(c){if(this.p==f){var d=V("gsc-configSetting");this.p=Ab(f,"0",this.V,"gsc-configSettingCheckbox");T(d,this.p);T(d,U(R["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=V("gsc-configSettingSubmit");T(e,yb(R[Va],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.p,this.V);this.p[Da]()}else this.p&&(this.p[Oa]?this.R(google[I].a.Ca):this.R(google[I].a.Db))};google[I].g=function(){google[I].a[J](this);this.z="web";this.Va="/GwebSearch";this.Fa="http://www.google.com/search";this.l=f;this.F=google[I].g.aa;this.H=this.wa=this.Qa=this.md=this.$a=f};P("google.search.WebSearch",google[I].g);gb(google[I].g,google[I].a);google[I].g.I="GwebSearch";Q(google[I].g,"RESULT_CLASS",google[I].g.I);google[I].g.Gb="cx";Q(google[I].g,"cxRestriction_CX",google[I].g.Gb);google[I].g.oc="cref";Q(google[I].g,"cxRestriction_CREF",google[I].g.oc);google[I].g.aa="none";
Q(google[I].g,"cxRestriction_NONE",google[I].g.aa);google[I].g.Jg=10;google[I].g.o=[];google[I].g.M=function(a,c,d,e,g){var i=0;a&&(i=ca(a,10));a=google[I].g.o[i];google[I].g.o[i]=f;a.ca(c,d,e,g)};Q(google[I].g,"RawCompletion",google[I].g.M);google[I].g[E].cg=function(a){var c=google[I].a.ma(google[I].g.o,this);google[I].g.M(c,a,200,f,200)};Q(google[I].g[E],"renderJson",google[I].g[E].cg);google[I].g[E].wj=function(a){return a[w](/\s+$/,"")[w](/^\s+/,"")};
google[I].g[E].ni=function(a){a=this.wj(a);return a[w](/\s+/g,"_")[db]()};
google[I].g[E].ra=function(a,c,d,e){d=d==f?google[I].a.ma(google[I].g.o,this):d;if(this.F==google[I].g.aa&&this.zk==google[I].a.fb)throw createException("The resultset size google.search.Search.FILTERED_CSE_RESULTSET can  only be used for querying filtered Custom Search Engines.");c=this.Ta(c==f?"google.search.WebSearch.RawCompletion":c,d,e);this.O&&(a=a+" "+this.O);if(this.l&&this.F!=google[I].g.aa&&this.md){var d=this.md,g=a;this.$a!=f&&(g=a+" more:"+this.$a);d=d[w](/__HL__/,google[I][L]);this.Qa=
d=d[w](/__QUERY__/,h(g))}this.l&&this.F==google[I].g.aa&&(a=a+" site:"+this.l);d="";this.l&&this.F!=google[I].g.aa&&(this.F==google[I].g.Gb?d=d+"&cx="+this.l:this.F==google[I].g.oc&&(d=d+"&cref="+h(this.l)),this.$a!=f&&(a=a+" more:"+this.$a));d=d+"&q="+h(a);this.wa&&(d=d+"&safe="+this.wa);this.H&&(d+=this.H);c+=d;this.w=d;if(e&&e!=0)this.w=this.w+"&start="+e;k.google[K].GoogleLocale&&(c+="&gl="+h(k.google[K].GoogleLocale));return c};
google[I].g[E].Ef=function(a){a.html&&delete a.html;var c=qb(R.dym,"gs-spelling");Z(c,"gs-result");var d=m[A]("a");o(d,a.anchor);c[s](d);a.html=c};Q(google[I].g[E],"createSpellingHtml",google[I].g[E].Ef);
google[I].g[E].Cf=function(a){a.html&&delete a.html;var c=V("gs-promotion");Z(c,"gs-result");var d,d=a.url,e=a[La],g=this.u(),i=U(f,"gs-title"),l=m[A]("a");l.href=d;e&&T(l,pb(e));r(l,"gs-title");g&&ma(l,g);i[s](l);T(c,i);d=sb(0,0);e=tb(d,0);T(c,d);if(a.image)d=a.image,d=vb(d.url,d[v],d[bb],"gs-promotion-image"),a.url&&(g=wb(a.url,"",this.u()),T(g,d),d=g),g=ub("gs-promotion-image-td"),T(g,d),T(e,g);if(a.bodyLines){var g=ub(),q=V();T(e,g);T(g,q);e=a.bodyLines;for(g=0;g<e[D];g++){var d=e[g],i=d[La],
l=d.url,u=d.visibleUrl,d=V("gs-snippet");l&&u&&(l=wb(l,u,this.u(),"gs-title"),T(d,l));i&&T(d,pb(i));T(q,d)}}d=qb(a.visibleUrl,"gs-visibleUrl");T(q,d);Z(d,"gs-visibleUrl-short");a.html=c};Q(google[I].g[E],"createPromotionHtml",google[I].g[E].Cf);google[I].g[E].K=function(a){a.html&&delete a.html;ma(a,this.u()||b);a.html=google[I].q.yc("webResult",a);this.Na(a.html)};Q(google[I].g[E],"createResultHtml",google[I].g[E].K);
google[I].g[E].Ka=function(a,c,d){this.Kb=this.Qa=f;var e=!1;a==f||typeof a=="string"&&a==""?(e=!1,this.l=f,this.F=google[I].g.aa,this.Kb=this.$a=f):typeof a=="string"?(e=a[Ca](/(^partner-pub-\d*:.*)|(^\d{21}:.*)/))?(this.l=a,this.F=google[I].g.Gb):(this.l=a,this.F=google[I].g.aa):a.siteUrl?(e=!1,this.l=a.siteUrl):a.cseId?(e=!0,this.l=a.cseId,this.F=google[I].g.Gb):a.crefUrl?(e=!0,this.l=a.crefUrl,this.F=google[I].g.oc,this.Kb=R["linked-cse-error-results"]):(e=!1,this.l=f,this.F=google[I].g.aa,this.$a=
f);if(e){if(c)this.$a=this.ni(c);if(d&&d[Ca](/__HL__/)&&d[Ca](/__QUERY__/))this.md=d;if(this.F==google[I].g.oc&&!this.l[Ca](/^http:\/\/www\.google\.com\/coop\/tools\/autocse\?referer=/)&&n[xa](n.random()*google[I].g.Jg)==0)(new Image).src="https://www.google.com/cse/tools/ping?cref="+h(this.l)+"&nocache="+Number(new Date)}};Q(google[I].g[E],"setSiteRestriction",google[I].g[E].Ka);
google[I].g[E].Y=function(a,c){if(a==google[I].a.ib)this.wa=c?c==google[I].a.Rc||c==google[I].a.Qc||c==google[I].a.Ye?c:f:f;if(a==google[I].a.hb)if(c)for(var d in c){var e=c[d];if(d=="lr"||d=="usg"||d=="filter"||d=="gl"||d=="richsnippet"||d=="sort")this.H==f?this.H="&":this.H+="&",this.H+=d+"="+h(e)}else this.H=f};Q(google[I].g[E],"setRestriction",google[I].g[E].Y);google[I].g[E].Z=function(a){google[I].a.fb==a?this.Ia=google[I].a.fb:google[I].a[E].Z[J](this,a)};
Q(google[I].g[E],"setResultSetSize",google[I].g[E].Z);google[I].NoOldNames||(j("GwebSearch",google[I].g),j("GbookSearch",google[I].m),j("GblogSearch",google[I].r),j("GvideoSearch",google[I].s),j("GnewsSearch",google[I].n),j("GlocalSearch",google[I].f),j("GimageSearch",google[I].c),j("GpatentSearch",google[I].j),j("GSearch",google[I].a),j("GSearchControl",google[I].b),j("GSearchForm",google[I].J),j("GsearcherOptions",google[I].D),j("GdrawOptions",google[I].A));google[I].q={};google[I].q.uh=function(a){google[I].q.vc.unshift(a);return google[I].q.vc};P("google.search.Csedr.addOverride",google[I].q.uh);google[I].q.vc=["base_",""];google[I].q.Oh=function(a,c){google[I].q.ud[a]||(google[I].q.ud[a]=eval("[function(Vars,render,html){with(Vars)return("+a+")}][0]"));return google[I].q.ud[a](c,google[I].q.yc,google[I].q.Pb)};google[I].q.ud={};google[I].q.Pb=function(a){var c=m.createDocumentFragment(),d=m[A]("div");for(o(d,a);d[B];)c[s](d[B]);return c};
google[I].q.yc=function(a){if(google[I].q.Td)m[Wa][s](google[I].q.Pb(google[I].q.Td)),google[I].q.Td=0;for(var c=0;!a[s];){if(c>=google[I].q.vc[D])return google[I].q.Pb(a+" not found");a=m[x](google[I].q.vc[c++]+a)||a}for(var d={},e=1;e<arguments[D];e++)for(c in arguments[e])d[c]=arguments[e][c];try{for(var g=google[I].q.Pb(""),i,l,e=0,q,u,z=function(a){a="data-"+a;u=(q=G.getAttribute(a))?google[I].q.Oh(q,d):"";i.removeAttribute&&i.removeAttribute(a);return q},G=a[B];G;G=l?G:G.nextSibling)if(i=G[Ga](!1),
G.nodeType!=1)(G.nodeType!=3||G.nodeValue[Ca](/\S/))&&g[s](i);else{z("foreach");if(!l&&q)d.Foreach=u&&typeof u[cb]=="function"?u:[u],c=0,l=1;if(l)if(c<d.Foreach[D])d.Cur=d.Foreach[d.Index=c++];else{l=0;continue}z("if")&&(e=0);if(q||z("elif"))if(e||!u)continue;else e=1;if(!z("attr")||u){if(g[s](i),q)for(var W in u)if(u[W]!=b)W=="class"?r(i,u[W]):W=="style"&&ib("msie")?i[H].cssText=u[W]:i[Fa](W,u[W])}else i=g;var Jb=z("body")?u&&u[s]?u:m.createTextNode(u):google[I].q.yc(G,d,z("vars")?u:{});try{Jb&&
i[s](Jb)}catch(Vb){}}return g}catch(Tb){return google[I].q.Pb(Tb[Ka]()+": "+q)}};P("google.search.Csedr.render",google[I].q.yc);google[I].q.Td=' <div style="display:none"> <div id="base_webResult"> <div class="gs-webResult gs-result" data-vars="{longUrl:function() { var i = unescapedUrl.indexOf(visibleUrl); return i < 1 ? visibleUrl : unescapedUrl.substring(i);}}"> <div data-if="Vars.richSnippet" data-attr="0" data-body="render(\'thumbnail\',richSnippet,{url:unescapedUrl,target:target})"></div> <div class="gs-title"> <a class="gs-title" data-attr="{href:unescapedUrl,target:target}" data-body="html(title)"></a> </div> <div class="gs-snippet" data-body="html(content)"></div> <div class="gs-visibleUrl gs-visibleUrl-short" data-body="visibleUrl"></div> <div class="gs-visibleUrl gs-visibleUrl-long" data-body="longUrl()"></div> <div data-if="Vars.richSnippet && Vars.richSnippet.action" class="gs-actions" data-body="render(\'action\',richSnippet,{url:unescapedUrl,target:target})"></div> </div> </div> <div id="base_thumbnail"> <div data-attr="0" data-vars="{tn:Vars.thumbnail && thumbnail.src ? thumbnail : {src:Vars.document && document.thumbnailUrl}}"> <div data-if="tn.src"> <a class="gs-image" data-attr="{href:url,target:target}"> <img style="display: none;" class="gs-image" data-attr="{src:tn.src, width:tn.width || 100, height: tn.height}" onload="this.style.display = \'inline\'; this.parentNode.parentNode.className = \'gs-image-box gs-web-image-box\';"/> </a> </div> </div> </div> <div id="base_action"> <div data-foreach="Vars.action" data-attr="0"> <div data-attr="{\'class\': \'gs-action \' + Cur[\'class\']}" data-if="Cur.url && Cur.label"> <a class="gs-action" data-attr="{href:Cur.url,target:target}" data-body="Cur.label"></a> </div> </div> </div> </div> ';
google.loader.loaded({"module":"search","version":"1.0","components":["default"]});
google.loader.eval.search = function() {eval(arguments[0]);};if (google.loader.eval.scripts && google.loader.eval.scripts['search']) {(function() {var scripts = google.loader.eval.scripts['search'];for (var i = 0; i < scripts.length; i++) {google.loader.eval.search(scripts[i]);}})();google.loader.eval.scripts['search'] = null;}})();