var gfc_qn=osapi,gfc_rn="ceil";gfc_1[gfc_].share=gfc_0c(24,function(){gfc_an();return gfc_d});gfc_Pf[gfc_].ceil=gfc_0c(20,function(){gfc_ra(this,gfc_k[gfc_rn](this[gfc_p]));gfc_Ma(this,gfc_k[gfc_rn](this[gfc_J]));return this});gfc_1[gfc_].Yi=gfc_0c(19,function(){var a=this.Kd;if(a.valid){this.d=this.Pg(this.Kd);this.$h(a[gfc_Pb])}else{this.Kd=gfc_c;this.render(a.actions,a[gfc_Pb],a.params)}this.Og()});gfc_1[gfc_].Tf=gfc_0c(14,function(){return this.Hb.pop()});
gfc_1[gfc_].yi=gfc_0c(5,function(a,b,c){return a?c<b?[]:a[gfc_fb](gfc_k.min(b,a[gfc_n]),gfc_k.min(c,a[gfc_n])):[]});
var gfc_sn=function(a){return a=gfc_i.friendconnect_serverBase+"/friendconnect/favicon?url="+escape(a)},gfc_6=function(a,b,c){this.Ka();this.Ir();var d=new gfc_O;d.set("members",{action:this.hv,callback:this.au});d.set("member-page",{action:this.gv,callback:this.$t});d.set("blocked-member-page",{action:this.av,callback:this.Wt});d.set("profile-friends-page",{action:this.mv,callback:this.eu});d.set("sitesData",{action:this.uv,callback:this.iu});d.set("viewerFriends",{action:this.zv,callback:this.ku});
d.set("profileData",{action:this.lv,callback:this.du});d.set("blockUser",{action:this.$u,callback:this.Vt});d.set("unblockUser",{action:this.xv,callback:this.ju});d.set("profileFriends",{action:this.nv,callback:this.fu});d.set("activityData",{action:this.ag,callback:this.ud});d.set("sendFriendRequest",{action:this.tv,callback:this.hu});d.set("sendFriendRequestResponse",{action:this.dv,callback:this.Bm});d.set("deleteActivity",{action:this.bg,callback:this.ud});d.set("requestAndProcessViewerNumWaitingMessages",
{action:this.Av,callback:this.mu});d.set("requestPromo",{action:this.ov,callback:this.gu});this.ob=gfc_c;this.Ux=new gfc_in("fc-members-options-menu",gfc_L(this.yt,this),gfc_L(this.xt,this),gfc_L(this.zt,this),0,gfc_i.friendconnect_serverBase,this.f("ENDCAP_LINK_COLOR")||"0000cc",this.f("CONTENT_TEXT_COLOR")||"000000");this.Gw=gfc_d;this.Ia=10;this.Nf=15;this.En=10;var e=gfc_Pg(gfc_Bg()),f=gfc_tn;this.bc=3;this.wc=8;this.bn=gfc_c;this.ra=this.wc*this.bc;this.slimTopCapHeight=19;this.tinyTopCapHeight=
8;this.isMessagingEnabled=a;this.isPromosEnabled=b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=gfc_c;this.Tb=new gfc_en;if(this.Uh()){a=(a=this.f(f.FACE_SIZE))?gfc_fa(a):32;a=a+6;this.bc=gfc_k[gfc_mb]((e[gfc_p]-10)/a);e=340;e=this.f(f.HEIGHT);b=this.f(f.NUMBER_ROWS);f=27;if(b){this.wc=gfc_fa(b);e=this.wc*a;this.bn=e+f}else if(e){e=gfc_fa(e)-96;this.wc=gfc_k.max(2,gfc_k[gfc_mb](e/a));this.bn=this.wc*a+f}this.ra=this.wc*this.bc}gfc_1[gfc_A](this,d)};gfc_6.inherits(gfc_1);
gfc_Ca(gfc_6[gfc_],function(){gfc_6.i[gfc_C][gfc_A](this);gfc_Nm("start");var a=gfc_e[gfc_o][gfc_Tb](),b=gfc_ka();if(a=b.profileId||a.profileId){b={};b[gfc_j[gfc_u][gfc_H].ID]=a;a=new gfc_j[gfc_u](b);this.render(["profileData","profileFriends","activityData"],"profile",{person:a})}else{a=["members","viewerFriends"];this.isMessagingEnabled&&a[gfc_m]("requestAndProcessViewerNumWaitingMessages");this.isPromosEnabled&&!this.Ob()&&a[gfc_m]("requestPromo");this.render(a,"faces")}});gfc_6[gfc_].e={};
gfc_6[gfc_].Ka=function(){this.e.MSG_SITE_MEMBERS="Members";this.e.MSG_BE_THE_FIRST="Be the first!";this.e.MSG_NO_SITE_MEMBERS="There are no members yet.";this.e.MSG_ALL_SITE_MEMBERS="All Members";this.e.MSG_ALL_BLOCKED_MEMBERS="All Blocked Members";this.e.MSG_NO_BLOCKED_MEMBERS="You have not blocked any members";this.e.MSG_YOUR_FRIENDS="Your Friends";this.e.MSG_ALL_YOUR_FRIENDS="All Your Friends";this.e.MSG_JFJ="Join and connect with others!";this.e.MSG_MANAGE="Manage members";this.e.MSG_SETTINGS=
"Settings";this.e.MSG_OPTIONS="Options";this.e.MSG_INVITE="Invite";this.e.MSG_MEMBERS_SHARE="Share this page";this.e.MSG_BACK="Back";this.e.MSG_BACK_TO_TOP="Home";this.e.MSG_VIEW_MY_PROFILE="View my profile";this.e.MSG_ABOUT_ME="About me";this.e.MSG_MORE="More \u00bb";this.e.MSG_SHOW_BLOCKED="Show blocked members \u00bb";this.e.MSG_SHOW_ALL="\u00ab Show all members";this.e.MSG_INVITE_YOUR_FRIENDS="Invite your friends";this.e.MSG_LINK_IN_NETWORKS="Link in your social networks";this.e.MSG_ACTIVITIES=
"Activities";this.e.MSG_ALL_ACTIVITIES="More activities";this.e.MSG_DELETE_THIS="Delete";this.e.MSG_SITES="Sites I've joined";this.e.MSG_ALL_SITES="More sites I've joined";this.e.MSG_LINKS="Links";this.e.MSG_ALL_LINKS="More links";this.e.MSG_NO_ACTIVITIES="No activities to show";this.e.MSG_ADD_AS_FRIEND="Add as friend";this.e.MSG_SEND_MESSAGE="Send a message";this.e.MSG_BLOCK_USER="Block this user";this.e.MSG_UNBLOCK_USER="Unblock this user";this.e.MSG_USER_IS_ADMIN="Administrator";this.e.MSG_JOIN=
"Join this site";this.e.MSG_OR="or";this.e.MSG_SIGN_IN="Sign in";this.e.MSG_SIGN_OUT="Sign out";this.e.MSG_PREVIOUS="\u00ab Previous";this.e.MSG_NEXT="Next \u00bb";this.e.MSG_NEWER="\u00ab Newer";this.e.MSG_OLDER="Older \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Accept all";this.e.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Friend Connect sites.";this.e.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Friend Connect sites.";this.e.MSG_HELP_BLOCKMEMBER=
"Blocking a visitor removes them from the members list and prevents them from interacting with other visitors on your site";this.e.MSG_INVITATION="Invitation:";this.e.MSG_SEND="Send";this.e.MSG_BLOCK="Block";this.e.MSG_IGNORE="Ignore";this.e.MSG_CANCEL="Cancel";this.e.MSG_SITE_SETTINGS="Site settings";this.e.MSG_INVITE_FRIENDS="Invite friends";this.e.MSG_ABOUT_FC="About Friend Connect";this.e.MSG_ALREADY_MEMBER="Already a member?";this.e.MSG_EDIT_PROFILE="Edit profile"};gfc_6[gfc_].ua={};
gfc_6[gfc_].Ir=function(){this.ua.MSG_SITE_MEMBERS="Followers";this.ua.MSG_NO_SITE_MEMBERS="There are no followers yet.";this.ua.MSG_SHOW_BLOCKED="Show blocked followers \u00bb";this.ua.MSG_SHOW_ALL="\u00ab Show all followers";this.ua.MSG_ALL_SITE_MEMBERS="All Followers";this.ua.MSG_ALL_BLOCKED_MEMBERS="All Blocked Followers";this.ua.MSG_NO_BLOCKED_MEMBERS="You have not blocked any followers";this.ua.MSG_LIKE_THIS_SITE="Like this blog?";this.ua.MSG_JOIN="Follow";this.ua.MSG_BACK_TO_TOP="Members";
this.ua.MSG_JFJ="Follow and connect with your friends!";this.ua.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Following blogs and Friend Connect sites.";this.ua.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Following blogs and Friend Connect sites."};
gfc_6[gfc_].O=function(a,b){var c=gfc_b;if(b[gfc_D]&&b[gfc_D].person){var d={},e=b[gfc_D].person[gfc_Mb]()+" is your friend";d.MSG_IS_FRIEND=e;e="You have invited "+(b[gfc_D].person[gfc_Mb]()+" to be your friend");d.MSG_IS_INVITED=e;e=b[gfc_D].person[gfc_Mb]()+"'s friends";d.MSG_PROFILE_FRIENDS=e;e="All "+(b[gfc_D].person[gfc_Mb]()+"'s friends");d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.g(a,f,d[f])}if(b.invitedBy&&b.invitedBy[gfc_Mb]()){d=gfc_ha[gfc_p]?gfc_ha[gfc_p]:gfc_ha[gfc_Ob][gfc_bb]+2;
c=(d-135)/8;d=(d-175)/8;c="View "+(gfc_Bm(b.invitedBy[gfc_Mb](),c)+"'s profile");d=gfc_Bm(b.invitedBy[gfc_Mb](),d)+" invited you to this site";this.g(a,"MSG_VIEW_INVITER_PROFILE",c);this.g(a,"MSG_INVITED_YOU",d);this.Gw=gfc_b;c=gfc_d}d=this.numWaitingMessages+" messages waiting for you.";if(this.isMessagingEnabled&&this.numWaitingMessages>0){c=gfc_d;this.g(a,"showWaitingMessages",gfc_b);if(this.isMessagingEnabled){this.g(a,"MSG_NUM_WAITING_MESSAGES",d);this.g(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING",
"View messages")}}if(b.friendRequests){if(b.friendRequests[gfc_8a]()>0)c=gfc_d;if(b.friendRequests[gfc_8a]()==1)d="New friend request \u00bb";else d=d="New friend requests ("+(b.friendRequests[gfc_8a]()+") \u00bb");this.g(a,"MSG_NEW_FRIEND_REQUESTS",d)}if(this.ob){if(this.Cl(this.ob.themeId))for(f in this.ua)this.g(a,f,this.ua[f]);this.ob.signInPrompt&&this.g(a,"MSG_JOIN",this.ob.signInPrompt);this.ob.signOutPrompt&&this.g(a,"MSG_SIGN_OUT",this.ob.signOutPrompt)}this.g(a,"isViewerAdmin",b.isViewerAdmin);
this.g(a,"isMessagingEnabled",this.isMessagingEnabled);this.g(a,"acceptMessages",this.io);this.g(a,"isViewingSelf",b.viewer&&b[gfc_D]&&b[gfc_D].person&&b.viewer[gfc_z]()==b[gfc_D].person[gfc_z]());d=gfc_d;if(b.owner)if(e=b.owner[gfc_I]("profileExtensions"))for(f in e)d=gfc_b;this.g(a,"communityHasProfile",d);this.g(a,"promoHtml",c?this.promoHtml:gfc_c);this.g(a,"insertHtml",function(g,h){gfc_ta(g,h)})};gfc_6[gfc_].Cl=function(a){return a=="blogger"};
gfc_6[gfc_].eh=function(a,b,c,d){gfc_9m({id:a,text:b,version:this.Cl(this.ob.themeId)?1:gfc_c,style:c},d)};
gfc_6[gfc_].Q=function(a){function b(e,f){d.g(a,e,gfc_L(f,d))}this.g(a,"facesPerRow",this.bc);for(var c in this.e)this.g(a,c,this.e[c]);var d=this;b("getThumbnail",this.Bc);b("map",this.map);b("elide",gfc_Bm);b("safeSlice",this.yi);b("showAllActivities",this.rw);b("transformActivity",this.oc);b("nextActivities",this.Vs);b("previousActivities",this.It);b("showAllLinks",this.tw);b("transformLink",this.gx);b("nextLinks",this.Zs);b("previousLinks",this.Kt);b("showAllSites",this.ww);b("transformSite",
this.hx);b("nextSites",this.gt);b("previousSites",this.Qt);b("showAllMembers",this.uw);b("showBlockedMembers",this.yw);b("showUnblockedMembers",this.Pw);b("nextMembers",this.$s);b("nextBlockedMembers",this.Ws);b("previousMembers",this.Lt);b("previousBlockedMembers",this.Jt);b("showAllProfileFriends",this.vw);b("nextProfileFriends",this.ft);b("previousProfileFriends",this.Pt);b("showAllViewerFriends",this.xw);b("nextViewerFriends",this.ht);b("previousViewerFriends",this.Rt);b("isHome",this.Sh);b("goBack",
this.uh);b("goBackToHome",this.Hw);b("invite",this.invite);b("editSettings",this.Cb);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.Wn);b("blockUser",this.xj);b("unblockUser",this.kx);b("goToInviteFriend",this.Sq);b("sendMessageDialog",this.Ov);b("goToBlockMember",this.Rq);b("goToEditProfile",this.Cb);b("goToViewerProfile",this.Tq);b("sendInvite",this.Nv);b("blockMember",this.Do);b("acceptFriendRequest",this.ho);b("ignoreFriendRequest",this.Hr);b("viewFriendRequests",this.ux);
b("acceptAllFriendRequests",this.fo);b("numPreviewFriends",this.Bq);b("numPreviewMembers",this.Cq);b("showInvitedBy",this.Iq)};
gfc_6[gfc_].Sk=function(a){a=gfc_k.max(1,a?this.wc-1:this.wc);var b=this.d[gfc_r].members?this.d[gfc_r].members[gfc_8a]():0,c=this.d[gfc_r].friends?this.d[gfc_r].friends[gfc_8a]():0;b=gfc_k[gfc_rn](b/this.bc);c=gfc_k[gfc_rn](c/this.bc);if(b>gfc_k[gfc_rn](a/2))if(c>gfc_k[gfc_mb](a/2)){b=gfc_k[gfc_rn](a/2);c=gfc_k[gfc_mb](a/2)}else b=gfc_k.max(0,a-c);else if(c>gfc_k[gfc_mb](a/2))c=gfc_k.max(0,a-b);b=b*this.bc;c=c*this.bc;return a={numMembers:b,numFriends:c}};gfc_6[gfc_].Cq=function(a){return this.Sk(a).numMembers};
gfc_6[gfc_].Bq=function(a){return this.Sk(a).numFriends};gfc_6[gfc_].gv=function(a,b){var c=gfc_j[gfc_G](),d={},e=gfc_j[gfc_x][gfc_oc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_C];d[e.MAX]=b.pageSize?b.pageSize:this.ra;var f=[gfc_j[gfc_u][gfc_H].ID,gfc_j[gfc_u][gfc_H][gfc__a],gfc_j[gfc_u][gfc_H][gfc_Lc]];d[e[gfc_rc]]=f;d[gfc_j[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;c.add(c[gfc_2b](gfc__d(),d),"ownerFriends");c[gfc_B](a)};
gfc_6[gfc_].$t=function(a){this.d[gfc_r].members=a.get("ownerFriends")[gfc_s]()};gfc_6[gfc_].av=function(a,b){var c=gfc_j[gfc_G](),d={},e=gfc_j[gfc_x][gfc_oc];d[e.FIRST]=b[gfc_C];d[e.MAX]=b.pageSize?b.pageSize:this.ra;d[gfc_j[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;e={};e[gfc_j[gfc_Ua][gfc_H][gfc_Kb]]=gfc_j[gfc_Ua].PersonId.OWNER;e[gfc_j[gfc_Ua][gfc_H][gfc_ob]]="BLOCKED";e[gfc_j[gfc_Ua][gfc_H][gfc_Za]]=1;e=gfc_j[gfc_Tc](e);c.add(c[gfc_2b](e,d),"blockedMembers");c[gfc_B](a)};
gfc_6[gfc_].Wt=function(a){this.d[gfc_r].blockedMembers=a.get("blockedMembers")[gfc_s]()};gfc_6[gfc_].mv=function(a,b){var c=gfc_j[gfc_G](),d=b&&b.person&&b.person[gfc_z]()||this.u[gfc_D].person[gfc_z](),e={},f=gfc_j[gfc_x][gfc_oc];e[f.FIRST]=b[gfc_C];e[f.MAX]=b.pageSize?b.pageSize:this.ra;d=this.fm(d);e[gfc_j[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;c.add(c[gfc_2b](d,e),"profileFriends");c[gfc_B](a)};
gfc_6[gfc_].fm=function(a){var b={};b[gfc_j[gfc_Ua][gfc_H][gfc_Kb]]=a;b[gfc_j[gfc_Ua][gfc_H][gfc_ob]]="FRIENDS";b[gfc_j[gfc_Ua][gfc_H][gfc_Za]]=1;return gfc_j[gfc_Tc](b)};gfc_6[gfc_].eu=function(a){this.d[gfc_r][gfc_D].friends=a.get("profileFriends")[gfc_s]()};gfc_6[gfc_].pj=function(a){for(var b=gfc_j[gfc_r].getDataContext(),c=0;c<a[gfc_n];c++){var d=a[c];d=b.getDataSet(d);if(!d||d.code)return gfc_d}return gfc_b};
gfc_6[gfc_].hv=function(a){var b=this.ra,c=!b||b==24;if(c&&gfc_j[gfc_r])if(this.pj(["ownerFriends","viewer","siteSettings","friendRequests"])){a(gfc_j[gfc_r].getDataContext()[gfc_s]());return}c=gfc_qn.newBatch();b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"};c.add("ownerFriends",gfc_qn.people.get(b));c.add("viewer",gfc_qn.people.getViewer());c.add("siteSettings",gfc_qn.extensions.get({command:"GetSiteSettings"}));c.add("friendRequests",gfc_qn.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'}));(b=gfc_ka().psinvite)&&c.add("invitedBy",gfc_qn.extensions.get({command:"DecodeInvitation",params:{token:b}}));c.execute(a)};gfc_6[gfc_].au=function(a,b){this.d[gfc_r].members=gfc_Sd(a.ownerFriends,gfc_Nd);this.d[gfc_r].viewer=gfc_Nd(a.viewer);this.Bm(a,b,gfc_b);this.ob=a[gfc_sc];var c=gfc_ka();if(c.psinvite)if(this.d[gfc_r].viewer==gfc_c||this.d[gfc_r].viewer==""){if(a.invitedBy)a.invitedBy.nickname=a.invitedBy.displayName;this.d[gfc_r].invitedBy=new gfc_j[gfc_u](a.invitedBy)}};
gfc_6[gfc_].zv=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_C]||b[gfc_C]==0,e=!c||c==20;if(d&&e&&gfc_j[gfc_r])if(this.pj(["friends","isViewerAdmin"])){a(gfc_j[gfc_r].getDataContext()[gfc_s]());return}d=gfc_qn.newBatch();c={userId:"@viewer",groupId:"@friends",count:c};if(b[gfc_C])c.startIndex=b[gfc_C];d.add("friends",gfc_qn.people.get(c));d.add("isViewerAdmin",gfc_qn.people.get({userId:"@viewer",groupId:"ADMINS"}));d.execute(a)};
gfc_6[gfc_].ku=function(a){var b=a.friends;if(b&&!b.error)this.d[gfc_r].friends=gfc_Sd(b,gfc_Nd);this.fn(a)};gfc_6[gfc_].Av=function(a){var b=gfc_j[gfc_G]();b.add(gfc_Qd("VIEWER"),"numWaitingMessages");b[gfc_B](a)};gfc_6[gfc_].mu=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_s]().numberOfWaitingMessages};
gfc_6[gfc_].ov=function(a){this.log("requesting promo");var b=new gfc_e[gfc_Fb];b=b.getLang()+(b[gfc_jc]()?"_"+b[gfc_jc]():"");var c=gfc_j[gfc_G]();c.add(gfc_Fd("GetPromo",{hl:b}),"promo");c[gfc_B](a)};gfc_6[gfc_].gu=function(a){this.log("processing promo");if((a=a.get("promo")[gfc_s]())&&a.promoCode!=-1){this.promoCode=a.promoCode;this.promoHtml=a.promoHtml}};
gfc_6[gfc_].qo=function(){for(var a=function(){this.promoHtml=gfc_c;for(var f=gfc_0f("div","fc-promo-main",gfc_R("peg")),g=0;g<f[gfc_n];g++)gfc_Tg(f[g],gfc_d);this.Y();this.log("Dismissing promo "+this.promoCode);f=gfc_j[gfc_G]();f.add(gfc_Fd("DismissPromo",{promoCode:this.promoCode}));f[gfc_B](gfc_L(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_0f("a","fc-promo-dismiss-link",gfc_R("peg")),c=0;c<b[gfc_n];c++){var d=b[c],e="click";gfc_Lh(d,e);gfc_Fh(d,e,gfc_L(a,
this))}};gfc_6[gfc_].fn=function(a){var b=a.isViewerAdmin;if(b&&!b.error)this.d[gfc_r].isViewerAdmin=b.list[gfc_n];else if(a.get&&a.get("isViewerAdmin"))if((a=a.get("isViewerAdmin"))&&!a[gfc_Bb]())this.d[gfc_r].isViewerAdmin=a[gfc_s]()[gfc_8a]()};gfc_6[gfc_].fo=function(a){var b=[];a.each(function(c){c={user:c[gfc_I](goog.opensocial.peoplesense.Invite[gfc_H].INVITER)[gfc_z](),action:"ACCEPT"};b[gfc_m](c)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.Mg,this),{friendRequestResponses:b})};
gfc_6[gfc_].Hw=function(){this.ka();this.render(["members","viewerFriends"],"faces")};gfc_6[gfc_].ho=function(a){a={user:a[gfc_z](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.Mg,this),{friendRequestResponses:[a]})};gfc_6[gfc_].ux=function(){this.ka();this.A("friend-requests")};gfc_6[gfc_].Wn=function(a){if(this.Ob()){this.ka();this.wx(a)}else gfc_Cd(a[gfc_z]())};
gfc_6[gfc_].wx=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_6[gfc_].uv=function(a,b){var c=gfc_j[gfc_G](),d=gfc_j[gfc_x][gfc_oc],e={};e[d.FIRST]=b&&b[gfc_C]?b[gfc_C]:0;var f=this.d[gfc_r][gfc_D].person[gfc_z]();e[d.MAX]=this.En;c.add(gfc_Xd(gfc_j[gfc_Tc]({userId:f}),e),"profileSites");c[gfc_B](a)};gfc_6[gfc_].iu=function(a){this.d[gfc_r][gfc_D].sites=a.get("profileSites")[gfc_s]()};
gfc_6[gfc_].lv=function(a,b){this.d[gfc_r].profile={};b=b||{};var c=b.person,d={};c=c[gfc_z]();var e=gfc_j[gfc_G](),f=[gfc_j[gfc_u][gfc_H].ID,gfc_j[gfc_u][gfc_H][gfc__a],gfc_j[gfc_u][gfc_H][gfc_Lc],gfc_j[gfc_u][gfc_H].ABOUT_ME,gfc_j[gfc_u][gfc_H].URLS,"profileExtensions"],g=gfc_j[gfc_x][gfc_oc];d[g[gfc_rc]]=f;d[gfc_j[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;e.add(e.newFetchPersonRequest(c,d),"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_Vd("VIEWER","ADMINS"),
"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.ob||e.add(gfc_Pd(),"siteSettings");e.add(gfc_Vd(c,"ADMINS"),"isAdmin");e.add(gfc_Vd(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_Qd(c),"canMessage");e[gfc_B](a)};
gfc_6[gfc_].ag=function(a,b){var c=b.person[gfc_z](),d=gfc_j[gfc_Tc]({userId:c}),e=gfc_j[gfc_G]();if(this.d[gfc_r].viewer&&c!=this.d[gfc_r].viewer[gfc_z]()||this.Ob())e.add(gfc_Ud(b.person[gfc_z](),"VIEWER"),"isProfileFriend");e.add(e[gfc_xb](d,{}),"activities");e[gfc_B](a)};
gfc_6[gfc_].ud=function(a,b){if(a.get("activities")[gfc_s]()!=gfc_c)this.d[gfc_r][gfc_D].activities=a.get("activities")[gfc_s]();var c=a.get("isProfileFriend");if(c)if(b&&this.d[gfc_r].viewer!=gfc_c&&this.d[gfc_r].viewer[gfc_z]()!=b.person[gfc_z]())this.d[gfc_r][gfc_D].isFriend=c[gfc_s]()[gfc_t]};
gfc_6[gfc_].du=function(a,b){var c=a.get("profile")[gfc_s]();this.d[gfc_r][gfc_D].person=c;this.d[gfc_r][gfc_D].person.externalProfileUrl=gfc_c;var d=c[gfc_I](gfc_j[gfc_u][gfc_H].URLS),e=[];if(d)for(var f=0;f<d[gfc_n];f++){var g=d[f];g[gfc_I](gfc_j.Url[gfc_H].TYPE)!="profile"&&g[gfc_I](gfc_j.Url[gfc_H].TYPE)!="externalProfile"&&e[gfc_m](g);if(g[gfc_I](gfc_j.Url[gfc_H].TYPE)=="externalProfile")this.d[gfc_r][gfc_D].person.externalProfileUrl=g[gfc_I](gfc_j.Url[gfc_H].ADDRESS)}this.d[gfc_r][gfc_D].links=
new gfc_un(e,this.Nf,0);this.d[gfc_r].owner=a.get("owner")[gfc_s]();this.d[gfc_r].viewer=a.get("viewer")[gfc_s]();if((d=this.d[gfc_r].viewer)&&b.person[gfc_z]()!=this.d[gfc_r].viewer[gfc_z]()){this.d[gfc_r][gfc_D].isAdmin=a.get("isAdmin")[gfc_s]();if(this.d[gfc_r][gfc_D].isAdmin)this.d[gfc_r][gfc_D].isAdmin=this.d[gfc_r][gfc_D].isAdmin[gfc_8a]();this.d[gfc_r][gfc_D].isBlocked=a.get("isBlocked")[gfc_s]();if(this.d[gfc_r][gfc_D].isBlocked)this.d[gfc_r][gfc_D].isBlocked=this.d[gfc_r][gfc_D].isBlocked[gfc_8a]()}c=
c[gfc_I]("profileExtensions");c=this.Tb.Ff(c,this.Tb.Oi);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=gfc_d;if(e.entryType=="SHORT_TEXT"||e.entryType=="LONG_TEXT"){if(e[gfc_t]&&e[gfc_t][gfc_ab]){g.body=[];g[gfc_Ob][gfc_m](e[gfc_t][gfc_ab]);h=gfc_b}}else if(e[gfc_t]&&e[gfc_t].choice&&e[gfc_t].choice[gfc_n]>0){g.body=[];for(h=0;h<e[gfc_t].choice[gfc_n];++h)g[gfc_Ob][gfc_m](e[gfc_t].choice[h][gfc_Hc]);h=gfc_b}h&&d[gfc_m](g)}this.d[gfc_r][gfc_D].profileExtensions=d;if(!this.ob)this.ob=a.get("siteSettings")[gfc_s]();
if(this.isMessagingEnabled){f=(f=a.get("canMessage"))&&f[gfc_s]().canSendMessage;this.d[gfc_r][gfc_D].canSendMessage=f}this.fn(a)};gfc_6[gfc_].xj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_6[gfc_].kx=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_6[gfc_].map=function(a,b){var c=[],d=gfc_L(function(e,f,g){e[gfc_m](f(g))},this,c,b);a.each(d);return c};gfc_6[gfc_].uw=function(){this.ka();this.A("members-page")};
gfc_6[gfc_].yw=function(){this.ka();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_6[gfc_].Pw=function(){this.Yi()};gfc_6[gfc_].$s=function(a){this.render(["member-page"],"members-page",{start:this.ra+a.getOffset()})};gfc_6[gfc_].Lt=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.ra})};gfc_6[gfc_].Ws=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.ra+a.getOffset()})};
gfc_6[gfc_].Jt=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.ra})};gfc_6[gfc_].xw=function(){this.ka();this.A("viewer-friends-page")};gfc_6[gfc_].ht=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.ra+a.getOffset()})};gfc_6[gfc_].Rt=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.ra})};gfc_6[gfc_].vw=function(){this.ka();this.A("profile-friends-page")};
gfc_6[gfc_].ft=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.ra+a.getOffset(),person:this.d[gfc_r][gfc_D].person})};gfc_6[gfc_].Pt=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.ra,person:this.d[gfc_r][gfc_D].person})};gfc_6[gfc_].tw=function(){this.ka();this.A("links")};gfc_6[gfc_].Zs=function(a){var b=this.Nf+a.getOffset();this.d[gfc_r][gfc_D].links=new gfc_un(a.all(),this.Nf,b);this.A("links")};
gfc_6[gfc_].Kt=function(a){var b=a.getOffset()-this.Nf;this.d[gfc_r][gfc_D].links=new gfc_un(a.all(),this.Nf,b);this.A("links")};gfc_6[gfc_].ww=function(){this.ka();this.A("sites")};gfc_6[gfc_].gt=function(a){this.render(["sitesData"],"sites",{start:this.En+a.getOffset()})};gfc_6[gfc_].Qt=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.En})};gfc_6[gfc_].rw=function(){this.ka();this.A("activities")};
gfc_6[gfc_].Vs=function(a){this.render(["activityData"],"activities",{start:this.Ia+a.getOffset()})};gfc_6[gfc_].It=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Ia})};gfc_6[gfc_].uf=function(a){this.render(["deleteActivity"],this.d[gfc_Pb],{activity:a})};gfc_6[gfc_].$u=function(a,b){var c=gfc_j[gfc_G]();c.add(gfc_Wd(b.person[gfc_z](),["BLOCKED"],[]),"block");this.od();c[gfc_B](a)};
gfc_6[gfc_].Vt=function(a){if(a=!a.get("block")[gfc_Bb]())this.d[gfc_r][gfc_D].isBlocked=gfc_b};gfc_6[gfc_].xv=function(a,b){var c=gfc_j[gfc_G]();c.add(gfc_Wd(b.person[gfc_z](),[],["BLOCKED"]),"unblock");this.od();c[gfc_B](a)};gfc_6[gfc_].ju=function(a){if(a=!a.get("unblock")[gfc_Bb]())this.d[gfc_r][gfc_D].isBlocked=gfc_d};
gfc_6[gfc_].bg=function(a,b){var c=b.activity,d=c[gfc_I](gfc_j[gfc_4b][gfc_H].ID);c=gfc_j[gfc_Tc]({userId:c[gfc_I](gfc_j[gfc_4b][gfc_H][gfc_Kb])});var e=gfc_j[gfc_G]();e.add(gfc_Gd(d),"delete");e.add(e[gfc_xb](c,{}),"activities");e[gfc_B](a)};
gfc_6[gfc_].oc=function(a){var b=gfc_hn,c=function(f){return f=f[gfc_q](/<a/g,"<a target='_top'")},d=gfc_c,e=this.d[gfc_r].viewer;if(e!=gfc_c&&a[gfc_I](gfc_j[gfc_4b][gfc_H][gfc_Kb])==this.d[gfc_r].viewer[gfc_z]())d=gfc_L(this.uf,this,a);(e=a[gfc_I](gfc_j[gfc_4b][gfc_H].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_i.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_fa(a[gfc_I](gfc_j[gfc_4b][gfc_H].POSTED_TIME))),link:a[gfc_I](gfc_j[gfc_4b][gfc_H].STREAM_URL,{escapeType:"none"}),
siteTitle:a[gfc_I](gfc_j[gfc_4b][gfc_H].STREAM_TITLE,{escapeType:"none"}),innerHTML:c(a[gfc_I](gfc_j[gfc_4b][gfc_H].TITLE,{escapeType:"none"})),body:c(a[gfc_I](gfc_j[gfc_4b][gfc_H].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_6[gfc_].hx=function(a){var b=gfc_e[gfc_mc].unescapeString,c=gfc_sn;return{icon:c(a[gfc_I](gfc_j[gfc_u][gfc_H][gfc_ac])),link:a[gfc_I](gfc_j[gfc_u][gfc_H][gfc_ac]),title:b(a[gfc_Mb]())}};
gfc_6[gfc_].gx=function(a){var b=gfc_e[gfc_mc].unescapeString,c=gfc_sn,d=a[gfc_I](gfc_j.Url[gfc_H].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_I](gfc_j.Url[gfc_H].LINK_TEXT))||d}};
gfc_6[gfc_].nv=function(a,b){var c=gfc_j[gfc_G](),d=b.person[gfc_z](),e={},f=gfc_j[gfc_x][gfc_oc];e[f[gfc_rc]]=[gfc_j[gfc_u][gfc_H].ID,gfc_j[gfc_u][gfc_H][gfc__a]];var g=this.fm(d),h={};h[gfc_j[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;c.add(c[gfc_2b](g,h),"friends");g={};g[f.FIRST]=this.xy;g[f.MAX]=this.wy;c.add(gfc_Xd(gfc_j[gfc_Tc]({userId:d}),g),"profileSites");e[f[gfc_rc]]=[gfc_j[gfc_u][gfc_H].ID,gfc_j[gfc_u][gfc_H][gfc__a],gfc_j[gfc_u][gfc_H][gfc_Lc],gfc_j[gfc_u][gfc_H].ABOUT_ME];
e[gfc_j[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_j.EscapeType.NONE;c[gfc_B](a)};gfc_6[gfc_].Hr=function(a){a={user:a[gfc_z](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.Mg,this),{friendRequestResponses:[a]})};gfc_6[gfc_].Mg=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_6[gfc_].tv=function(a,b){var c=b[gfc_D],d=gfc_j[gfc_G]();d.add(gfc_Hd(c[gfc_z](),b[gfc_Ib]),"friendRequest");this.od();d[gfc_B](a)};
gfc_6[gfc_].hu=function(a){if(!a.get("friendRequest")[gfc_Bb]())this.d[gfc_r][gfc_D].isInvited=gfc_b};gfc_6[gfc_].dv=function(a,b){var c=gfc_qn.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",gfc_qn.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_e[gfc_8b].stringify(d)+"}"}));c.add("friendRequests",gfc_qn.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.od();c.execute(a)};gfc_6[gfc_].Sq=function(){this.ka();this.A("invite-friend")};
gfc_6[gfc_].Ov=function(a){if(this.isMessagingEnabled){a=a[gfc_I](gfc_j[gfc_u][gfc_H].ID);this.Pv(a)}};gfc_6[gfc_].Pv=function(a){if(this.isMessagingEnabled){a="/friendconnect/messaging/compose?recipientId="+a;var b=570,c=395;gfc_1m(a,gfc_h(b),gfc_h(c))}};gfc_1[gfc_].io=function(){var a="/friendconnect/messaging/accept",b=570,c=375;gfc_1m(a,gfc_h(b),gfc_h(c));return gfc_d};gfc_6[gfc_].Rq=function(){this.ka();this.A("block-member")};gfc_6[gfc_].Tq=function(){this.Wn(this.d[gfc_r].viewer)};
gfc_6[gfc_].Nv=function(a){this.Tf();a={profile:a};var b=gfc_R("inviteMessage");if(b)a.message=gfc_gf(b);this.render(["sendFriendRequest"],"profile",a)};gfc_6[gfc_].Do=function(a){this.Tf();this.xj(a)};gfc_6[gfc_].Bm=function(a,b,c){c=c||gfc_d;this.d[gfc_r].friendRequests=gfc_Sd(a.friendRequests,gfc_Jd);b["next-view"]=this.d[gfc_r].friendRequests[gfc_8a]()>0?"friend-requests":"faces";c||gfc_Nm("friend")};
gfc_6[gfc_].fu=function(a){this.d[gfc_r][gfc_D].sites=a.get("profileSites")[gfc_s]();this.d[gfc_r][gfc_D].friends=a.get("friends")[gfc_s]()};gfc_6[gfc_].Iq=function(){return this.Gw};gfc_6[gfc_].Y=function(){this.Ux.rebuild();this.qo();gfc_e[gfc_Wa].adjustHeight()};gfc_6[gfc_].yt=function(a){return a=gfc_S("span",{"class":"fc-cap-link-big"},gfc_S("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.Rg())};
gfc_6[gfc_].xt=function(){var a=[];a[a[gfc_n]]=gfc_S("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);a[a[gfc_n]]=this.isSocialShareEnabled?gfc_S("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE):gfc_S("div",{"class":"goog-menuitem menuaction-invite"},this.e.MSG_INVITE_FRIENDS);if(this.d[gfc_r].isViewerAdmin&&!this.Ob())a[a[gfc_n]]=gfc_S("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE);a[a[gfc_n]]=gfc_S("div",{"class":"goog-menuitem menuaction-signout"},
this.ob.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_n]]=gfc_S("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_n]]=gfc_S("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_S("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_6[gfc_].zt=function(a){a[gfc_ub]();a=a[gfc_Rb].h()[gfc_5a];if(a[gfc_Yb]("menuaction-settings"))this.Cb();else if(a[gfc_Yb]("menuaction-invite"))this.invite();else if(a[gfc_Yb]("menuaction-share"))this.share();else if(a[gfc_Yb]("menuaction-signout"))this.signout();else if(a[gfc_Yb]("menuaction-manage"))this.Xq();else if(a[gfc_Yb]("menuaction-aboutfc")){a=gfc_i[gfc_0a](gfc_Um()+"/friendconnect");a[gfc_5b]()}};
gfc_6[gfc_].Xq=function(){var a={},b=gfc_e[gfc_o][gfc_nb]().canvas;gfc_Nm("lightbox");gfc_e[gfc_o].requestNavigateTo(b,a);return gfc_d};var gfc_tn=function(a){for(var b={},c=0;c<a[gfc_n];++c)b[a[c]]=a[c];return b}(["HEIGHT","BORDER_COLOR","CONTENT_BG_COLOR","CONTENT_HEADLINE_COLOR","CONTENT_LINK_COLOR","CONTENT_SECONDARY_TEXT_COLOR","CONTENT_SECONDARY_LINK_COLOR","CONTENT_TEXT_COLOR","ENDCAP_BG_COLOR","ENDCAP_LINK_COLOR","ENDCAP_TEXT_COLOR","FACE_SIZE","NUMBER_ROWS"]);
gfc_6[gfc_].r=function(){var a=gfc_tn,b=[],c=0;gfc_fa(this.f(a.HEIGHT));if(this.Uh())b[c++]=this.j(".fc-thumbnail img {height:%spx;width:%spx}",this.f(a.FACE_SIZE));b[c++]=this.j(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.bn);b[c++]=this.j(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.f(a.BORDER_COLOR));if(this.Df())if(this.nl("profile"))b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n";else if(this.Xh())b[c++]=".fc-topcap {height: 0px;}\n";else b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n";if(this.Ob())b[c++]=".fc-userpic-caption {margin-left: 59px;}\n";else b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";if(this.Xh())b[c++]=".fc-topcap-color {background-color: white;}\n";else b[c++]=this.j(".fc-topcap-color {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));
if(this.Dl())b[c++]=".fc-botcap-short {background-color: white;}\n";else b[c++]=this.j(".fc-botcap-short {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",
this.f(a.ENDCAP_TEXT_COLOR));b[c++]=this.j(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.f(a.ENDCAP_LINK_COLOR));b[c++]=this.j(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.f(a.CONTENT_BG_COLOR));b[c++]=this.j(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.f(a.CONTENT_LINK_COLOR));b[c++]=this.j(".fc-members,.fc-members-canvas {color:%s;}\n",this.f(a.CONTENT_TEXT_COLOR));b[c++]=this.j(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.f(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.j(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.f(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.j(".fc-sectitle {color: %s;}\n",
this.f(a.CONTENT_HEADLINE_COLOR));return gfc_6.i.r[gfc_A](this)+b[gfc_K]("\n")};gfc_M("goog.peoplesense.gadget.Members",gfc_6);gfc_M("goog.peoplesense.gadget.Members.start",gfc_6[gfc_C]);var gfc_un=function(a,b,c){gfc_j.Collection[gfc_A](this,a[gfc_fb](c,c+b),c,a[gfc_n]);this.Cx=a;this.ja=b};gfc_un.inherits(gfc_j.Collection);gfc_un[gfc_].all=function(){return this.Cx};gfc_un[gfc_].sb=function(){return this.ja};gfc_M("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_un[gfc_].all);
gfc_M("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_un[gfc_].sb);
